#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 148
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 23
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum {
  sym_comment = 1,
  sym_dinkus = 2,
  sym_page_break = 3,
  sym_line_break = 4,
  anon_sym_STAR = 5,
  anon_sym__ = 6,
  anon_sym_BQUOTE = 7,
  sym__newline = 8,
  sym__newline_plus = 9,
  sym_head3 = 10,
  sym_head2 = 11,
  sym_head1 = 12,
  sym_fence_open = 13,
  sym_fence_close = 14,
  sym_code_lang = 15,
  sym__code_line = 16,
  sym_curly_open = 17,
  sym_curly_close = 18,
  sym_code_inline_content = 19,
  sym_exclamation = 20,
  sym_question = 21,
  sym_caret = 22,
  sym_equal = 23,
  sym_square_open = 24,
  sym_square_close = 25,
  sym_resource = 26,
  sym_paren_open = 27,
  sym_paren_close = 28,
  sym_label = 29,
  sym_text = 30,
  sym_document = 31,
  sym__block = 32,
  sym_chapter = 33,
  sym_section = 34,
  sym_subsection = 35,
  sym_code_block_lang = 36,
  sym_code_block = 37,
  sym_code_content = 38,
  sym_paragraph = 39,
  sym__end_block = 40,
  sym__inline = 41,
  sym_bold = 42,
  sym_italic = 43,
  sym_monospaced = 44,
  sym_view_label = 45,
  sym_view = 46,
  sym_link_label = 47,
  sym_link = 48,
  sym_footnote_ref = 49,
  sym_footnote_desc = 50,
  sym_include = 51,
  sym_code_inline_lang = 52,
  sym_code_inline = 53,
  aux_sym_document_repeat1 = 54,
  aux_sym_chapter_repeat1 = 55,
  aux_sym_code_content_repeat1 = 56,
  aux_sym_paragraph_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_dinkus] = "dinkus",
  [sym_page_break] = "page_break",
  [sym_line_break] = "line_break",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [anon_sym_BQUOTE] = "`",
  [sym__newline] = "_newline",
  [sym__newline_plus] = "_newline_plus",
  [sym_head3] = "head3",
  [sym_head2] = "head2",
  [sym_head1] = "head1",
  [sym_fence_open] = "fence_open",
  [sym_fence_close] = "fence_close",
  [sym_code_lang] = "code_lang",
  [sym__code_line] = "_code_line",
  [sym_curly_open] = "curly_open",
  [sym_curly_close] = "curly_close",
  [sym_code_inline_content] = "code_inline_content",
  [sym_exclamation] = "exclamation",
  [sym_question] = "question",
  [sym_caret] = "caret",
  [sym_equal] = "equal",
  [sym_square_open] = "square_open",
  [sym_square_close] = "square_close",
  [sym_resource] = "resource",
  [sym_paren_open] = "paren_open",
  [sym_paren_close] = "paren_close",
  [sym_label] = "label",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_chapter] = "chapter",
  [sym_section] = "section",
  [sym_subsection] = "subsection",
  [sym_code_block_lang] = "code_block_lang",
  [sym_code_block] = "code_block",
  [sym_code_content] = "code_content",
  [sym_paragraph] = "paragraph",
  [sym__end_block] = "_end_block",
  [sym__inline] = "_inline",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [sym_monospaced] = "monospaced",
  [sym_view_label] = "view_label",
  [sym_view] = "view",
  [sym_link_label] = "link_label",
  [sym_link] = "link",
  [sym_footnote_ref] = "footnote_ref",
  [sym_footnote_desc] = "footnote_desc",
  [sym_include] = "include",
  [sym_code_inline_lang] = "code_inline_lang",
  [sym_code_inline] = "code_inline",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_chapter_repeat1] = "chapter_repeat1",
  [aux_sym_code_content_repeat1] = "code_content_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_dinkus] = sym_dinkus,
  [sym_page_break] = sym_page_break,
  [sym_line_break] = sym_line_break,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [sym__newline] = sym__newline,
  [sym__newline_plus] = sym__newline_plus,
  [sym_head3] = sym_head3,
  [sym_head2] = sym_head2,
  [sym_head1] = sym_head1,
  [sym_fence_open] = sym_fence_open,
  [sym_fence_close] = sym_fence_close,
  [sym_code_lang] = sym_code_lang,
  [sym__code_line] = sym__code_line,
  [sym_curly_open] = sym_curly_open,
  [sym_curly_close] = sym_curly_close,
  [sym_code_inline_content] = sym_code_inline_content,
  [sym_exclamation] = sym_exclamation,
  [sym_question] = sym_question,
  [sym_caret] = sym_caret,
  [sym_equal] = sym_equal,
  [sym_square_open] = sym_square_open,
  [sym_square_close] = sym_square_close,
  [sym_resource] = sym_resource,
  [sym_paren_open] = sym_paren_open,
  [sym_paren_close] = sym_paren_close,
  [sym_label] = sym_label,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_chapter] = sym_chapter,
  [sym_section] = sym_section,
  [sym_subsection] = sym_subsection,
  [sym_code_block_lang] = sym_code_block_lang,
  [sym_code_block] = sym_code_block,
  [sym_code_content] = sym_code_content,
  [sym_paragraph] = sym_paragraph,
  [sym__end_block] = sym__end_block,
  [sym__inline] = sym__inline,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [sym_monospaced] = sym_monospaced,
  [sym_view_label] = sym_view_label,
  [sym_view] = sym_view,
  [sym_link_label] = sym_link_label,
  [sym_link] = sym_link,
  [sym_footnote_ref] = sym_footnote_ref,
  [sym_footnote_desc] = sym_footnote_desc,
  [sym_include] = sym_include,
  [sym_code_inline_lang] = sym_code_inline_lang,
  [sym_code_inline] = sym_code_inline,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_chapter_repeat1] = aux_sym_chapter_repeat1,
  [aux_sym_code_content_repeat1] = aux_sym_code_content_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_dinkus] = {
    .visible = true,
    .named = true,
  },
  [sym_page_break] = {
    .visible = true,
    .named = true,
  },
  [sym_line_break] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__newline_plus] = {
    .visible = false,
    .named = true,
  },
  [sym_head3] = {
    .visible = true,
    .named = true,
  },
  [sym_head2] = {
    .visible = true,
    .named = true,
  },
  [sym_head1] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_open] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_close] = {
    .visible = true,
    .named = true,
  },
  [sym_code_lang] = {
    .visible = true,
    .named = true,
  },
  [sym__code_line] = {
    .visible = false,
    .named = true,
  },
  [sym_curly_open] = {
    .visible = true,
    .named = true,
  },
  [sym_curly_close] = {
    .visible = true,
    .named = true,
  },
  [sym_code_inline_content] = {
    .visible = true,
    .named = true,
  },
  [sym_exclamation] = {
    .visible = true,
    .named = true,
  },
  [sym_question] = {
    .visible = true,
    .named = true,
  },
  [sym_caret] = {
    .visible = true,
    .named = true,
  },
  [sym_equal] = {
    .visible = true,
    .named = true,
  },
  [sym_square_open] = {
    .visible = true,
    .named = true,
  },
  [sym_square_close] = {
    .visible = true,
    .named = true,
  },
  [sym_resource] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_open] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_close] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_chapter] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_subsection] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block_lang] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_code_content] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym__end_block] = {
    .visible = false,
    .named = true,
  },
  [sym__inline] = {
    .visible = false,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_monospaced] = {
    .visible = true,
    .named = true,
  },
  [sym_view_label] = {
    .visible = true,
    .named = true,
  },
  [sym_view] = {
    .visible = true,
    .named = true,
  },
  [sym_link_label] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_footnote_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_footnote_desc] = {
    .visible = true,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym_code_inline_lang] = {
    .visible = true,
    .named = true,
  },
  [sym_code_inline] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chapter_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 16,
  [17] = 13,
  [18] = 15,
  [19] = 16,
  [20] = 16,
  [21] = 15,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 22,
  [41] = 24,
  [42] = 23,
  [43] = 32,
  [44] = 28,
  [45] = 33,
  [46] = 30,
  [47] = 31,
  [48] = 29,
  [49] = 27,
  [50] = 25,
  [51] = 26,
  [52] = 23,
  [53] = 24,
  [54] = 22,
  [55] = 55,
  [56] = 26,
  [57] = 57,
  [58] = 58,
  [59] = 25,
  [60] = 27,
  [61] = 61,
  [62] = 32,
  [63] = 29,
  [64] = 31,
  [65] = 30,
  [66] = 33,
  [67] = 28,
  [68] = 68,
  [69] = 69,
  [70] = 69,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 69,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 87,
  [94] = 86,
  [95] = 85,
  [96] = 96,
  [97] = 97,
  [98] = 71,
  [99] = 72,
  [100] = 73,
  [101] = 77,
  [102] = 79,
  [103] = 80,
  [104] = 92,
  [105] = 87,
  [106] = 86,
  [107] = 85,
  [108] = 97,
  [109] = 97,
  [110] = 71,
  [111] = 72,
  [112] = 73,
  [113] = 77,
  [114] = 79,
  [115] = 80,
  [116] = 116,
  [117] = 81,
  [118] = 92,
  [119] = 119,
  [120] = 120,
  [121] = 91,
  [122] = 90,
  [123] = 89,
  [124] = 88,
  [125] = 75,
  [126] = 76,
  [127] = 78,
  [128] = 116,
  [129] = 81,
  [130] = 130,
  [131] = 131,
  [132] = 116,
  [133] = 91,
  [134] = 90,
  [135] = 89,
  [136] = 88,
  [137] = 75,
  [138] = 76,
  [139] = 78,
  [140] = 131,
  [141] = 130,
  [142] = 120,
  [143] = 119,
  [144] = 131,
  [145] = 130,
  [146] = 120,
  [147] = 119,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == '_') ADVANCE(11);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '~') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '_') ADVANCE(11);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '<') ADVANCE(8);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_dinkus);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_page_break);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_line_break);
      if (lookahead == '<') ADVANCE(7);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(1);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 4},
  [7] = {.lex_state = 0, .external_lex_state = 4},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0, .external_lex_state = 4},
  [10] = {.lex_state = 0, .external_lex_state = 5},
  [11] = {.lex_state = 0, .external_lex_state = 5},
  [12] = {.lex_state = 0, .external_lex_state = 5},
  [13] = {.lex_state = 0, .external_lex_state = 5},
  [14] = {.lex_state = 0, .external_lex_state = 5},
  [15] = {.lex_state = 0, .external_lex_state = 5},
  [16] = {.lex_state = 0, .external_lex_state = 5},
  [17] = {.lex_state = 0, .external_lex_state = 5},
  [18] = {.lex_state = 0, .external_lex_state = 5},
  [19] = {.lex_state = 0, .external_lex_state = 5},
  [20] = {.lex_state = 0, .external_lex_state = 5},
  [21] = {.lex_state = 0, .external_lex_state = 5},
  [22] = {.lex_state = 0, .external_lex_state = 6},
  [23] = {.lex_state = 0, .external_lex_state = 6},
  [24] = {.lex_state = 0, .external_lex_state = 6},
  [25] = {.lex_state = 0, .external_lex_state = 3},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 0, .external_lex_state = 3},
  [29] = {.lex_state = 0, .external_lex_state = 3},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 0, .external_lex_state = 3},
  [34] = {.lex_state = 0, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 0, .external_lex_state = 2},
  [38] = {.lex_state = 0, .external_lex_state = 2},
  [39] = {.lex_state = 0, .external_lex_state = 2},
  [40] = {.lex_state = 0, .external_lex_state = 7},
  [41] = {.lex_state = 0, .external_lex_state = 7},
  [42] = {.lex_state = 0, .external_lex_state = 7},
  [43] = {.lex_state = 0, .external_lex_state = 4},
  [44] = {.lex_state = 0, .external_lex_state = 4},
  [45] = {.lex_state = 0, .external_lex_state = 4},
  [46] = {.lex_state = 0, .external_lex_state = 4},
  [47] = {.lex_state = 0, .external_lex_state = 4},
  [48] = {.lex_state = 0, .external_lex_state = 4},
  [49] = {.lex_state = 0, .external_lex_state = 4},
  [50] = {.lex_state = 0, .external_lex_state = 4},
  [51] = {.lex_state = 0, .external_lex_state = 4},
  [52] = {.lex_state = 2, .external_lex_state = 8},
  [53] = {.lex_state = 2, .external_lex_state = 8},
  [54] = {.lex_state = 2, .external_lex_state = 8},
  [55] = {.lex_state = 0, .external_lex_state = 9},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 10},
  [58] = {.lex_state = 0, .external_lex_state = 10},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0, .external_lex_state = 9},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 11},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0, .external_lex_state = 12},
  [72] = {.lex_state = 0, .external_lex_state = 12},
  [73] = {.lex_state = 0, .external_lex_state = 12},
  [74] = {.lex_state = 0, .external_lex_state = 13},
  [75] = {.lex_state = 0, .external_lex_state = 14},
  [76] = {.lex_state = 0, .external_lex_state = 14},
  [77] = {.lex_state = 0, .external_lex_state = 15},
  [78] = {.lex_state = 0, .external_lex_state = 14},
  [79] = {.lex_state = 0, .external_lex_state = 15},
  [80] = {.lex_state = 0, .external_lex_state = 15},
  [81] = {.lex_state = 0, .external_lex_state = 16},
  [82] = {.lex_state = 0, .external_lex_state = 17},
  [83] = {.lex_state = 0, .external_lex_state = 13},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 0, .external_lex_state = 12},
  [88] = {.lex_state = 0, .external_lex_state = 16},
  [89] = {.lex_state = 0, .external_lex_state = 16},
  [90] = {.lex_state = 0, .external_lex_state = 16},
  [91] = {.lex_state = 0, .external_lex_state = 16},
  [92] = {.lex_state = 0, .external_lex_state = 18},
  [93] = {.lex_state = 0, .external_lex_state = 12},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0, .external_lex_state = 12},
  [98] = {.lex_state = 0, .external_lex_state = 12},
  [99] = {.lex_state = 0, .external_lex_state = 12},
  [100] = {.lex_state = 0, .external_lex_state = 12},
  [101] = {.lex_state = 0, .external_lex_state = 15},
  [102] = {.lex_state = 0, .external_lex_state = 15},
  [103] = {.lex_state = 0, .external_lex_state = 15},
  [104] = {.lex_state = 0, .external_lex_state = 18},
  [105] = {.lex_state = 0, .external_lex_state = 12},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0, .external_lex_state = 12},
  [109] = {.lex_state = 0, .external_lex_state = 12},
  [110] = {.lex_state = 0, .external_lex_state = 12},
  [111] = {.lex_state = 0, .external_lex_state = 12},
  [112] = {.lex_state = 0, .external_lex_state = 12},
  [113] = {.lex_state = 0, .external_lex_state = 15},
  [114] = {.lex_state = 0, .external_lex_state = 15},
  [115] = {.lex_state = 0, .external_lex_state = 15},
  [116] = {.lex_state = 0, .external_lex_state = 19},
  [117] = {.lex_state = 0, .external_lex_state = 16},
  [118] = {.lex_state = 0, .external_lex_state = 18},
  [119] = {.lex_state = 0, .external_lex_state = 20},
  [120] = {.lex_state = 0, .external_lex_state = 20},
  [121] = {.lex_state = 0, .external_lex_state = 16},
  [122] = {.lex_state = 0, .external_lex_state = 16},
  [123] = {.lex_state = 0, .external_lex_state = 16},
  [124] = {.lex_state = 0, .external_lex_state = 16},
  [125] = {.lex_state = 0, .external_lex_state = 14},
  [126] = {.lex_state = 0, .external_lex_state = 14},
  [127] = {.lex_state = 0, .external_lex_state = 14},
  [128] = {.lex_state = 0, .external_lex_state = 19},
  [129] = {.lex_state = 0, .external_lex_state = 16},
  [130] = {.lex_state = 0, .external_lex_state = 20},
  [131] = {.lex_state = 0, .external_lex_state = 20},
  [132] = {.lex_state = 0, .external_lex_state = 19},
  [133] = {.lex_state = 0, .external_lex_state = 16},
  [134] = {.lex_state = 0, .external_lex_state = 16},
  [135] = {.lex_state = 0, .external_lex_state = 16},
  [136] = {.lex_state = 0, .external_lex_state = 16},
  [137] = {.lex_state = 0, .external_lex_state = 14},
  [138] = {.lex_state = 0, .external_lex_state = 14},
  [139] = {.lex_state = 0, .external_lex_state = 14},
  [140] = {.lex_state = 0, .external_lex_state = 20},
  [141] = {.lex_state = 0, .external_lex_state = 20},
  [142] = {.lex_state = 0, .external_lex_state = 20},
  [143] = {.lex_state = 0, .external_lex_state = 20},
  [144] = {.lex_state = 0, .external_lex_state = 20},
  [145] = {.lex_state = 0, .external_lex_state = 20},
  [146] = {.lex_state = 0, .external_lex_state = 20},
  [147] = {.lex_state = 0, .external_lex_state = 20},
};

enum {
  ts_external_token__newline = 0,
  ts_external_token__newline_plus = 1,
  ts_external_token_head3 = 2,
  ts_external_token_head2 = 3,
  ts_external_token_head1 = 4,
  ts_external_token_fence_open = 5,
  ts_external_token_fence_close = 6,
  ts_external_token_code_lang = 7,
  ts_external_token__code_line = 8,
  ts_external_token_curly_open = 9,
  ts_external_token_curly_close = 10,
  ts_external_token_code_inline_content = 11,
  ts_external_token_exclamation = 12,
  ts_external_token_question = 13,
  ts_external_token_caret = 14,
  ts_external_token_equal = 15,
  ts_external_token_square_open = 16,
  ts_external_token_square_close = 17,
  ts_external_token_resource = 18,
  ts_external_token_paren_open = 19,
  ts_external_token_paren_close = 20,
  ts_external_token_label = 21,
  ts_external_token_text = 22,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__newline_plus] = sym__newline_plus,
  [ts_external_token_head3] = sym_head3,
  [ts_external_token_head2] = sym_head2,
  [ts_external_token_head1] = sym_head1,
  [ts_external_token_fence_open] = sym_fence_open,
  [ts_external_token_fence_close] = sym_fence_close,
  [ts_external_token_code_lang] = sym_code_lang,
  [ts_external_token__code_line] = sym__code_line,
  [ts_external_token_curly_open] = sym_curly_open,
  [ts_external_token_curly_close] = sym_curly_close,
  [ts_external_token_code_inline_content] = sym_code_inline_content,
  [ts_external_token_exclamation] = sym_exclamation,
  [ts_external_token_question] = sym_question,
  [ts_external_token_caret] = sym_caret,
  [ts_external_token_equal] = sym_equal,
  [ts_external_token_square_open] = sym_square_open,
  [ts_external_token_square_close] = sym_square_close,
  [ts_external_token_resource] = sym_resource,
  [ts_external_token_paren_open] = sym_paren_open,
  [ts_external_token_paren_close] = sym_paren_close,
  [ts_external_token_label] = sym_label,
  [ts_external_token_text] = sym_text,
};

static const bool ts_external_scanner_states[21][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_head3] = true,
    [ts_external_token_head2] = true,
    [ts_external_token_head1] = true,
    [ts_external_token_fence_open] = true,
    [ts_external_token_fence_close] = true,
    [ts_external_token_code_lang] = true,
    [ts_external_token__code_line] = true,
    [ts_external_token_curly_open] = true,
    [ts_external_token_curly_close] = true,
    [ts_external_token_code_inline_content] = true,
    [ts_external_token_exclamation] = true,
    [ts_external_token_question] = true,
    [ts_external_token_caret] = true,
    [ts_external_token_equal] = true,
    [ts_external_token_square_open] = true,
    [ts_external_token_square_close] = true,
    [ts_external_token_resource] = true,
    [ts_external_token_paren_open] = true,
    [ts_external_token_paren_close] = true,
    [ts_external_token_label] = true,
    [ts_external_token_text] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token_head3] = true,
    [ts_external_token_head2] = true,
    [ts_external_token_head1] = true,
    [ts_external_token_fence_open] = true,
    [ts_external_token_curly_open] = true,
    [ts_external_token_exclamation] = true,
    [ts_external_token_question] = true,
    [ts_external_token_caret] = true,
    [ts_external_token_equal] = true,
    [ts_external_token_square_open] = true,
    [ts_external_token_text] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_head3] = true,
    [ts_external_token_head2] = true,
    [ts_external_token_head1] = true,
    [ts_external_token_fence_open] = true,
    [ts_external_token_curly_open] = true,
    [ts_external_token_exclamation] = true,
    [ts_external_token_question] = true,
    [ts_external_token_caret] = true,
    [ts_external_token_equal] = true,
    [ts_external_token_square_open] = true,
    [ts_external_token_text] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_curly_open] = true,
    [ts_external_token_exclamation] = true,
    [ts_external_token_question] = true,
    [ts_external_token_caret] = true,
    [ts_external_token_equal] = true,
    [ts_external_token_square_open] = true,
    [ts_external_token_text] = true,
  },
  [5] = {
    [ts_external_token_curly_open] = true,
    [ts_external_token_exclamation] = true,
    [ts_external_token_question] = true,
    [ts_external_token_caret] = true,
    [ts_external_token_equal] = true,
    [ts_external_token_square_open] = true,
    [ts_external_token_text] = true,
  },
  [6] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_head3] = true,
    [ts_external_token_head2] = true,
    [ts_external_token_head1] = true,
    [ts_external_token_fence_open] = true,
    [ts_external_token_curly_open] = true,
    [ts_external_token_exclamation] = true,
    [ts_external_token_question] = true,
    [ts_external_token_caret] = true,
    [ts_external_token_equal] = true,
    [ts_external_token_square_open] = true,
    [ts_external_token_paren_open] = true,
    [ts_external_token_text] = true,
  },
  [7] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_curly_open] = true,
    [ts_external_token_exclamation] = true,
    [ts_external_token_question] = true,
    [ts_external_token_caret] = true,
    [ts_external_token_equal] = true,
    [ts_external_token_square_open] = true,
    [ts_external_token_paren_open] = true,
    [ts_external_token_text] = true,
  },
  [8] = {
    [ts_external_token_paren_open] = true,
  },
  [9] = {
    [ts_external_token_fence_close] = true,
    [ts_external_token__code_line] = true,
  },
  [10] = {
    [ts_external_token__code_line] = true,
  },
  [11] = {
    [ts_external_token__newline] = true,
    [ts_external_token_code_lang] = true,
  },
  [12] = {
    [ts_external_token_square_close] = true,
  },
  [13] = {
    [ts_external_token_fence_close] = true,
  },
  [14] = {
    [ts_external_token_label] = true,
  },
  [15] = {
    [ts_external_token_paren_close] = true,
  },
  [16] = {
    [ts_external_token_resource] = true,
  },
  [17] = {
    [ts_external_token__newline] = true,
  },
  [18] = {
    [ts_external_token_curly_close] = true,
  },
  [19] = {
    [ts_external_token_code_inline_content] = true,
  },
  [20] = {
    [ts_external_token_square_open] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_dinkus] = ACTIONS(1),
    [sym_page_break] = ACTIONS(1),
    [sym_line_break] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__newline_plus] = ACTIONS(1),
    [sym_head3] = ACTIONS(1),
    [sym_head2] = ACTIONS(1),
    [sym_head1] = ACTIONS(1),
    [sym_fence_open] = ACTIONS(1),
    [sym_fence_close] = ACTIONS(1),
    [sym_code_lang] = ACTIONS(1),
    [sym__code_line] = ACTIONS(1),
    [sym_curly_open] = ACTIONS(1),
    [sym_curly_close] = ACTIONS(1),
    [sym_code_inline_content] = ACTIONS(1),
    [sym_exclamation] = ACTIONS(1),
    [sym_question] = ACTIONS(1),
    [sym_caret] = ACTIONS(1),
    [sym_equal] = ACTIONS(1),
    [sym_square_open] = ACTIONS(1),
    [sym_square_close] = ACTIONS(1),
    [sym_resource] = ACTIONS(1),
    [sym_paren_open] = ACTIONS(1),
    [sym_paren_close] = ACTIONS(1),
    [sym_label] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(96),
    [sym__block] = STATE(2),
    [sym_chapter] = STATE(2),
    [sym_section] = STATE(2),
    [sym_subsection] = STATE(2),
    [sym_code_block_lang] = STATE(2),
    [sym_code_block] = STATE(2),
    [sym_paragraph] = STATE(2),
    [sym__inline] = STATE(4),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_monospaced] = STATE(4),
    [sym_view_label] = STATE(4),
    [sym_view] = STATE(4),
    [sym_link_label] = STATE(4),
    [sym_link] = STATE(4),
    [sym_footnote_ref] = STATE(4),
    [sym_footnote_desc] = STATE(4),
    [sym_include] = STATE(4),
    [sym_code_inline_lang] = STATE(4),
    [sym_code_inline] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_dinkus] = ACTIONS(5),
    [sym_page_break] = ACTIONS(5),
    [sym_line_break] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_BQUOTE] = ACTIONS(13),
    [sym__newline] = ACTIONS(5),
    [sym_head3] = ACTIONS(15),
    [sym_head2] = ACTIONS(17),
    [sym_head1] = ACTIONS(19),
    [sym_fence_open] = ACTIONS(21),
    [sym_curly_open] = ACTIONS(23),
    [sym_exclamation] = ACTIONS(25),
    [sym_question] = ACTIONS(27),
    [sym_caret] = ACTIONS(29),
    [sym_equal] = ACTIONS(31),
    [sym_square_open] = ACTIONS(33),
    [sym_text] = ACTIONS(5),
  },
  [2] = {
    [sym__block] = STATE(3),
    [sym_chapter] = STATE(3),
    [sym_section] = STATE(3),
    [sym_subsection] = STATE(3),
    [sym_code_block_lang] = STATE(3),
    [sym_code_block] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym__inline] = STATE(4),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_monospaced] = STATE(4),
    [sym_view_label] = STATE(4),
    [sym_view] = STATE(4),
    [sym_link_label] = STATE(4),
    [sym_link] = STATE(4),
    [sym_footnote_ref] = STATE(4),
    [sym_footnote_desc] = STATE(4),
    [sym_include] = STATE(4),
    [sym_code_inline_lang] = STATE(4),
    [sym_code_inline] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_comment] = ACTIONS(5),
    [sym_dinkus] = ACTIONS(5),
    [sym_page_break] = ACTIONS(5),
    [sym_line_break] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_BQUOTE] = ACTIONS(13),
    [sym__newline] = ACTIONS(5),
    [sym_head3] = ACTIONS(15),
    [sym_head2] = ACTIONS(17),
    [sym_head1] = ACTIONS(19),
    [sym_fence_open] = ACTIONS(21),
    [sym_curly_open] = ACTIONS(23),
    [sym_exclamation] = ACTIONS(25),
    [sym_question] = ACTIONS(27),
    [sym_caret] = ACTIONS(29),
    [sym_equal] = ACTIONS(31),
    [sym_square_open] = ACTIONS(33),
    [sym_text] = ACTIONS(5),
  },
  [3] = {
    [sym__block] = STATE(3),
    [sym_chapter] = STATE(3),
    [sym_section] = STATE(3),
    [sym_subsection] = STATE(3),
    [sym_code_block_lang] = STATE(3),
    [sym_code_block] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym__inline] = STATE(4),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_monospaced] = STATE(4),
    [sym_view_label] = STATE(4),
    [sym_view] = STATE(4),
    [sym_link_label] = STATE(4),
    [sym_link] = STATE(4),
    [sym_footnote_ref] = STATE(4),
    [sym_footnote_desc] = STATE(4),
    [sym_include] = STATE(4),
    [sym_code_inline_lang] = STATE(4),
    [sym_code_inline] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_comment] = ACTIONS(39),
    [sym_dinkus] = ACTIONS(39),
    [sym_page_break] = ACTIONS(39),
    [sym_line_break] = ACTIONS(42),
    [anon_sym_STAR] = ACTIONS(45),
    [anon_sym__] = ACTIONS(48),
    [anon_sym_BQUOTE] = ACTIONS(51),
    [sym__newline] = ACTIONS(39),
    [sym_head3] = ACTIONS(54),
    [sym_head2] = ACTIONS(57),
    [sym_head1] = ACTIONS(60),
    [sym_fence_open] = ACTIONS(63),
    [sym_curly_open] = ACTIONS(66),
    [sym_exclamation] = ACTIONS(69),
    [sym_question] = ACTIONS(72),
    [sym_caret] = ACTIONS(75),
    [sym_equal] = ACTIONS(78),
    [sym_square_open] = ACTIONS(81),
    [sym_text] = ACTIONS(39),
  },
  [4] = {
    [sym__inline] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_monospaced] = STATE(5),
    [sym_view_label] = STATE(5),
    [sym_view] = STATE(5),
    [sym_link_label] = STATE(5),
    [sym_link] = STATE(5),
    [sym_footnote_ref] = STATE(5),
    [sym_footnote_desc] = STATE(5),
    [sym_include] = STATE(5),
    [sym_code_inline_lang] = STATE(5),
    [sym_code_inline] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(84),
    [sym_comment] = ACTIONS(86),
    [sym_dinkus] = ACTIONS(86),
    [sym_page_break] = ACTIONS(86),
    [sym_line_break] = ACTIONS(88),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_BQUOTE] = ACTIONS(13),
    [sym__newline] = ACTIONS(86),
    [sym__newline_plus] = ACTIONS(90),
    [sym_head3] = ACTIONS(84),
    [sym_head2] = ACTIONS(84),
    [sym_head1] = ACTIONS(84),
    [sym_fence_open] = ACTIONS(84),
    [sym_curly_open] = ACTIONS(23),
    [sym_exclamation] = ACTIONS(25),
    [sym_question] = ACTIONS(27),
    [sym_caret] = ACTIONS(29),
    [sym_equal] = ACTIONS(31),
    [sym_square_open] = ACTIONS(33),
    [sym_text] = ACTIONS(86),
  },
  [5] = {
    [sym__inline] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_monospaced] = STATE(5),
    [sym_view_label] = STATE(5),
    [sym_view] = STATE(5),
    [sym_link_label] = STATE(5),
    [sym_link] = STATE(5),
    [sym_footnote_ref] = STATE(5),
    [sym_footnote_desc] = STATE(5),
    [sym_include] = STATE(5),
    [sym_code_inline_lang] = STATE(5),
    [sym_code_inline] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(92),
    [sym_comment] = ACTIONS(94),
    [sym_dinkus] = ACTIONS(94),
    [sym_page_break] = ACTIONS(94),
    [sym_line_break] = ACTIONS(97),
    [anon_sym_STAR] = ACTIONS(100),
    [anon_sym__] = ACTIONS(103),
    [anon_sym_BQUOTE] = ACTIONS(106),
    [sym__newline] = ACTIONS(94),
    [sym__newline_plus] = ACTIONS(92),
    [sym_head3] = ACTIONS(92),
    [sym_head2] = ACTIONS(92),
    [sym_head1] = ACTIONS(92),
    [sym_fence_open] = ACTIONS(92),
    [sym_curly_open] = ACTIONS(109),
    [sym_exclamation] = ACTIONS(112),
    [sym_question] = ACTIONS(115),
    [sym_caret] = ACTIONS(118),
    [sym_equal] = ACTIONS(121),
    [sym_square_open] = ACTIONS(124),
    [sym_text] = ACTIONS(94),
  },
  [6] = {
    [sym__end_block] = STATE(38),
    [sym__inline] = STATE(9),
    [sym_bold] = STATE(9),
    [sym_italic] = STATE(9),
    [sym_monospaced] = STATE(9),
    [sym_view_label] = STATE(9),
    [sym_view] = STATE(9),
    [sym_link_label] = STATE(9),
    [sym_link] = STATE(9),
    [sym_footnote_ref] = STATE(9),
    [sym_footnote_desc] = STATE(9),
    [sym_include] = STATE(9),
    [sym_code_inline_lang] = STATE(9),
    [sym_code_inline] = STATE(9),
    [aux_sym_chapter_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(127),
    [sym_dinkus] = ACTIONS(127),
    [sym_page_break] = ACTIONS(127),
    [sym_line_break] = ACTIONS(129),
    [anon_sym_STAR] = ACTIONS(131),
    [anon_sym__] = ACTIONS(133),
    [anon_sym_BQUOTE] = ACTIONS(135),
    [sym__newline] = ACTIONS(137),
    [sym__newline_plus] = ACTIONS(137),
    [sym_curly_open] = ACTIONS(139),
    [sym_exclamation] = ACTIONS(141),
    [sym_question] = ACTIONS(143),
    [sym_caret] = ACTIONS(145),
    [sym_equal] = ACTIONS(147),
    [sym_square_open] = ACTIONS(149),
    [sym_text] = ACTIONS(127),
  },
  [7] = {
    [sym__end_block] = STATE(36),
    [sym__inline] = STATE(9),
    [sym_bold] = STATE(9),
    [sym_italic] = STATE(9),
    [sym_monospaced] = STATE(9),
    [sym_view_label] = STATE(9),
    [sym_view] = STATE(9),
    [sym_link_label] = STATE(9),
    [sym_link] = STATE(9),
    [sym_footnote_ref] = STATE(9),
    [sym_footnote_desc] = STATE(9),
    [sym_include] = STATE(9),
    [sym_code_inline_lang] = STATE(9),
    [sym_code_inline] = STATE(9),
    [aux_sym_chapter_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(127),
    [sym_dinkus] = ACTIONS(127),
    [sym_page_break] = ACTIONS(127),
    [sym_line_break] = ACTIONS(129),
    [anon_sym_STAR] = ACTIONS(131),
    [anon_sym__] = ACTIONS(133),
    [anon_sym_BQUOTE] = ACTIONS(135),
    [sym__newline] = ACTIONS(151),
    [sym__newline_plus] = ACTIONS(151),
    [sym_curly_open] = ACTIONS(139),
    [sym_exclamation] = ACTIONS(141),
    [sym_question] = ACTIONS(143),
    [sym_caret] = ACTIONS(145),
    [sym_equal] = ACTIONS(147),
    [sym_square_open] = ACTIONS(149),
    [sym_text] = ACTIONS(127),
  },
  [8] = {
    [sym__end_block] = STATE(37),
    [sym__inline] = STATE(9),
    [sym_bold] = STATE(9),
    [sym_italic] = STATE(9),
    [sym_monospaced] = STATE(9),
    [sym_view_label] = STATE(9),
    [sym_view] = STATE(9),
    [sym_link_label] = STATE(9),
    [sym_link] = STATE(9),
    [sym_footnote_ref] = STATE(9),
    [sym_footnote_desc] = STATE(9),
    [sym_include] = STATE(9),
    [sym_code_inline_lang] = STATE(9),
    [sym_code_inline] = STATE(9),
    [aux_sym_chapter_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(127),
    [sym_dinkus] = ACTIONS(127),
    [sym_page_break] = ACTIONS(127),
    [sym_line_break] = ACTIONS(129),
    [anon_sym_STAR] = ACTIONS(131),
    [anon_sym__] = ACTIONS(133),
    [anon_sym_BQUOTE] = ACTIONS(135),
    [sym__newline] = ACTIONS(153),
    [sym__newline_plus] = ACTIONS(153),
    [sym_curly_open] = ACTIONS(139),
    [sym_exclamation] = ACTIONS(141),
    [sym_question] = ACTIONS(143),
    [sym_caret] = ACTIONS(145),
    [sym_equal] = ACTIONS(147),
    [sym_square_open] = ACTIONS(149),
    [sym_text] = ACTIONS(127),
  },
  [9] = {
    [sym__inline] = STATE(9),
    [sym_bold] = STATE(9),
    [sym_italic] = STATE(9),
    [sym_monospaced] = STATE(9),
    [sym_view_label] = STATE(9),
    [sym_view] = STATE(9),
    [sym_link_label] = STATE(9),
    [sym_link] = STATE(9),
    [sym_footnote_ref] = STATE(9),
    [sym_footnote_desc] = STATE(9),
    [sym_include] = STATE(9),
    [sym_code_inline_lang] = STATE(9),
    [sym_code_inline] = STATE(9),
    [aux_sym_chapter_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(155),
    [sym_dinkus] = ACTIONS(155),
    [sym_page_break] = ACTIONS(155),
    [sym_line_break] = ACTIONS(158),
    [anon_sym_STAR] = ACTIONS(161),
    [anon_sym__] = ACTIONS(164),
    [anon_sym_BQUOTE] = ACTIONS(167),
    [sym__newline] = ACTIONS(170),
    [sym__newline_plus] = ACTIONS(170),
    [sym_curly_open] = ACTIONS(172),
    [sym_exclamation] = ACTIONS(175),
    [sym_question] = ACTIONS(178),
    [sym_caret] = ACTIONS(181),
    [sym_equal] = ACTIONS(184),
    [sym_square_open] = ACTIONS(187),
    [sym_text] = ACTIONS(155),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(131), 1,
      anon_sym_STAR,
    ACTIONS(133), 1,
      anon_sym__,
    ACTIONS(135), 1,
      anon_sym_BQUOTE,
    ACTIONS(139), 1,
      sym_curly_open,
    ACTIONS(141), 1,
      sym_exclamation,
    ACTIONS(143), 1,
      sym_question,
    ACTIONS(145), 1,
      sym_caret,
    ACTIONS(147), 1,
      sym_equal,
    ACTIONS(149), 1,
      sym_square_open,
    ACTIONS(192), 1,
      sym_line_break,
    ACTIONS(190), 4,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
    STATE(7), 14,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_view_label,
      sym_view,
      sym_link_label,
      sym_link,
      sym_footnote_ref,
      sym_footnote_desc,
      sym_include,
      sym_code_inline_lang,
      sym_code_inline,
      aux_sym_chapter_repeat1,
  [53] = 12,
    ACTIONS(131), 1,
      anon_sym_STAR,
    ACTIONS(133), 1,
      anon_sym__,
    ACTIONS(135), 1,
      anon_sym_BQUOTE,
    ACTIONS(139), 1,
      sym_curly_open,
    ACTIONS(141), 1,
      sym_exclamation,
    ACTIONS(143), 1,
      sym_question,
    ACTIONS(145), 1,
      sym_caret,
    ACTIONS(147), 1,
      sym_equal,
    ACTIONS(149), 1,
      sym_square_open,
    ACTIONS(196), 1,
      sym_line_break,
    ACTIONS(194), 4,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
    STATE(8), 14,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_view_label,
      sym_view,
      sym_link_label,
      sym_link,
      sym_footnote_ref,
      sym_footnote_desc,
      sym_include,
      sym_code_inline_lang,
      sym_code_inline,
      aux_sym_chapter_repeat1,
  [106] = 12,
    ACTIONS(131), 1,
      anon_sym_STAR,
    ACTIONS(133), 1,
      anon_sym__,
    ACTIONS(135), 1,
      anon_sym_BQUOTE,
    ACTIONS(139), 1,
      sym_curly_open,
    ACTIONS(141), 1,
      sym_exclamation,
    ACTIONS(143), 1,
      sym_question,
    ACTIONS(145), 1,
      sym_caret,
    ACTIONS(147), 1,
      sym_equal,
    ACTIONS(149), 1,
      sym_square_open,
    ACTIONS(200), 1,
      sym_line_break,
    ACTIONS(198), 4,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
    STATE(6), 14,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_view_label,
      sym_view,
      sym_link_label,
      sym_link,
      sym_footnote_ref,
      sym_footnote_desc,
      sym_include,
      sym_code_inline_lang,
      sym_code_inline,
      aux_sym_chapter_repeat1,
  [159] = 12,
    ACTIONS(204), 1,
      sym_line_break,
    ACTIONS(206), 1,
      anon_sym_STAR,
    ACTIONS(208), 1,
      anon_sym__,
    ACTIONS(210), 1,
      anon_sym_BQUOTE,
    ACTIONS(212), 1,
      sym_curly_open,
    ACTIONS(214), 1,
      sym_exclamation,
    ACTIONS(216), 1,
      sym_question,
    ACTIONS(218), 1,
      sym_caret,
    ACTIONS(220), 1,
      sym_equal,
    ACTIONS(222), 1,
      sym_square_open,
    ACTIONS(202), 4,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
    STATE(70), 13,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_view_label,
      sym_view,
      sym_link_label,
      sym_link,
      sym_footnote_ref,
      sym_footnote_desc,
      sym_include,
      sym_code_inline_lang,
      sym_code_inline,
  [211] = 12,
    ACTIONS(206), 1,
      anon_sym_STAR,
    ACTIONS(208), 1,
      anon_sym__,
    ACTIONS(210), 1,
      anon_sym_BQUOTE,
    ACTIONS(212), 1,
      sym_curly_open,
    ACTIONS(214), 1,
      sym_exclamation,
    ACTIONS(216), 1,
      sym_question,
    ACTIONS(218), 1,
      sym_caret,
    ACTIONS(220), 1,
      sym_equal,
    ACTIONS(222), 1,
      sym_square_open,
    ACTIONS(226), 1,
      sym_line_break,
    ACTIONS(224), 4,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
    STATE(84), 13,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_view_label,
      sym_view,
      sym_link_label,
      sym_link,
      sym_footnote_ref,
      sym_footnote_desc,
      sym_include,
      sym_code_inline_lang,
      sym_code_inline,
  [263] = 12,
    ACTIONS(206), 1,
      anon_sym_STAR,
    ACTIONS(208), 1,
      anon_sym__,
    ACTIONS(210), 1,
      anon_sym_BQUOTE,
    ACTIONS(212), 1,
      sym_curly_open,
    ACTIONS(214), 1,
      sym_exclamation,
    ACTIONS(216), 1,
      sym_question,
    ACTIONS(218), 1,
      sym_caret,
    ACTIONS(220), 1,
      sym_equal,
    ACTIONS(222), 1,
      sym_square_open,
    ACTIONS(230), 1,
      sym_line_break,
    ACTIONS(228), 4,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
    STATE(107), 13,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_view_label,
      sym_view,
      sym_link_label,
      sym_link,
      sym_footnote_ref,
      sym_footnote_desc,
      sym_include,
      sym_code_inline_lang,
      sym_code_inline,
  [315] = 12,
    ACTIONS(206), 1,
      anon_sym_STAR,
    ACTIONS(208), 1,
      anon_sym__,
    ACTIONS(210), 1,
      anon_sym_BQUOTE,
    ACTIONS(212), 1,
      sym_curly_open,
    ACTIONS(214), 1,
      sym_exclamation,
    ACTIONS(216), 1,
      sym_question,
    ACTIONS(218), 1,
      sym_caret,
    ACTIONS(220), 1,
      sym_equal,
    ACTIONS(222), 1,
      sym_square_open,
    ACTIONS(234), 1,
      sym_line_break,
    ACTIONS(232), 4,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
    STATE(106), 13,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_view_label,
      sym_view,
      sym_link_label,
      sym_link,
      sym_footnote_ref,
      sym_footnote_desc,
      sym_include,
      sym_code_inline_lang,
      sym_code_inline,
  [367] = 12,
    ACTIONS(206), 1,
      anon_sym_STAR,
    ACTIONS(208), 1,
      anon_sym__,
    ACTIONS(210), 1,
      anon_sym_BQUOTE,
    ACTIONS(212), 1,
      sym_curly_open,
    ACTIONS(214), 1,
      sym_exclamation,
    ACTIONS(216), 1,
      sym_question,
    ACTIONS(218), 1,
      sym_caret,
    ACTIONS(220), 1,
      sym_equal,
    ACTIONS(222), 1,
      sym_square_open,
    ACTIONS(238), 1,
      sym_line_break,
    ACTIONS(236), 4,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
    STATE(69), 13,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_view_label,
      sym_view,
      sym_link_label,
      sym_link,
      sym_footnote_ref,
      sym_footnote_desc,
      sym_include,
      sym_code_inline_lang,
      sym_code_inline,
  [419] = 12,
    ACTIONS(206), 1,
      anon_sym_STAR,
    ACTIONS(208), 1,
      anon_sym__,
    ACTIONS(210), 1,
      anon_sym_BQUOTE,
    ACTIONS(212), 1,
      sym_curly_open,
    ACTIONS(214), 1,
      sym_exclamation,
    ACTIONS(216), 1,
      sym_question,
    ACTIONS(218), 1,
      sym_caret,
    ACTIONS(220), 1,
      sym_equal,
    ACTIONS(222), 1,
      sym_square_open,
    ACTIONS(242), 1,
      sym_line_break,
    ACTIONS(240), 4,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
    STATE(95), 13,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_view_label,
      sym_view,
      sym_link_label,
      sym_link,
      sym_footnote_ref,
      sym_footnote_desc,
      sym_include,
      sym_code_inline_lang,
      sym_code_inline,
  [471] = 12,
    ACTIONS(206), 1,
      anon_sym_STAR,
    ACTIONS(208), 1,
      anon_sym__,
    ACTIONS(210), 1,
      anon_sym_BQUOTE,
    ACTIONS(212), 1,
      sym_curly_open,
    ACTIONS(214), 1,
      sym_exclamation,
    ACTIONS(216), 1,
      sym_question,
    ACTIONS(218), 1,
      sym_caret,
    ACTIONS(220), 1,
      sym_equal,
    ACTIONS(222), 1,
      sym_square_open,
    ACTIONS(246), 1,
      sym_line_break,
    ACTIONS(244), 4,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
    STATE(94), 13,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_view_label,
      sym_view,
      sym_link_label,
      sym_link,
      sym_footnote_ref,
      sym_footnote_desc,
      sym_include,
      sym_code_inline_lang,
      sym_code_inline,
  [523] = 12,
    ACTIONS(206), 1,
      anon_sym_STAR,
    ACTIONS(208), 1,
      anon_sym__,
    ACTIONS(210), 1,
      anon_sym_BQUOTE,
    ACTIONS(212), 1,
      sym_curly_open,
    ACTIONS(214), 1,
      sym_exclamation,
    ACTIONS(216), 1,
      sym_question,
    ACTIONS(218), 1,
      sym_caret,
    ACTIONS(220), 1,
      sym_equal,
    ACTIONS(222), 1,
      sym_square_open,
    ACTIONS(250), 1,
      sym_line_break,
    ACTIONS(248), 4,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
    STATE(86), 13,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_view_label,
      sym_view,
      sym_link_label,
      sym_link,
      sym_footnote_ref,
      sym_footnote_desc,
      sym_include,
      sym_code_inline_lang,
      sym_code_inline,
  [575] = 12,
    ACTIONS(206), 1,
      anon_sym_STAR,
    ACTIONS(208), 1,
      anon_sym__,
    ACTIONS(210), 1,
      anon_sym_BQUOTE,
    ACTIONS(212), 1,
      sym_curly_open,
    ACTIONS(214), 1,
      sym_exclamation,
    ACTIONS(216), 1,
      sym_question,
    ACTIONS(218), 1,
      sym_caret,
    ACTIONS(220), 1,
      sym_equal,
    ACTIONS(222), 1,
      sym_square_open,
    ACTIONS(254), 1,
      sym_line_break,
    ACTIONS(252), 4,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
    STATE(85), 13,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_view_label,
      sym_view,
      sym_link_label,
      sym_link,
      sym_footnote_ref,
      sym_footnote_desc,
      sym_include,
      sym_code_inline_lang,
      sym_code_inline,
  [627] = 3,
    ACTIONS(260), 1,
      sym_paren_open,
    ACTIONS(258), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(256), 19,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [656] = 3,
    ACTIONS(266), 1,
      sym_paren_open,
    ACTIONS(264), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(262), 19,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [685] = 3,
    ACTIONS(272), 1,
      sym_paren_open,
    ACTIONS(270), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(268), 19,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [714] = 2,
    ACTIONS(276), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(274), 19,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [740] = 2,
    ACTIONS(280), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(278), 19,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [766] = 2,
    ACTIONS(284), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(282), 19,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [792] = 2,
    ACTIONS(288), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(286), 19,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [818] = 2,
    ACTIONS(292), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(290), 19,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [844] = 2,
    ACTIONS(296), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(294), 19,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [870] = 2,
    ACTIONS(300), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(298), 19,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [896] = 2,
    ACTIONS(304), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(302), 19,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [922] = 2,
    ACTIONS(308), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(306), 19,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [948] = 2,
    ACTIONS(312), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(310), 18,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [973] = 2,
    ACTIONS(316), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(314), 18,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [998] = 2,
    ACTIONS(320), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(318), 18,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1023] = 2,
    ACTIONS(324), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(322), 18,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1048] = 2,
    ACTIONS(328), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(326), 18,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1073] = 2,
    ACTIONS(332), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(330), 18,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1098] = 3,
    ACTIONS(334), 1,
      sym_paren_open,
    ACTIONS(258), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(256), 14,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1122] = 3,
    ACTIONS(336), 1,
      sym_paren_open,
    ACTIONS(270), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(268), 14,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1146] = 3,
    ACTIONS(338), 1,
      sym_paren_open,
    ACTIONS(264), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(262), 14,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1170] = 2,
    ACTIONS(304), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(302), 14,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1191] = 2,
    ACTIONS(288), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(286), 14,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1212] = 2,
    ACTIONS(308), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(306), 14,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1233] = 2,
    ACTIONS(296), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(294), 14,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1254] = 2,
    ACTIONS(300), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(298), 14,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1275] = 2,
    ACTIONS(292), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(290), 14,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1296] = 2,
    ACTIONS(284), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(282), 14,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1317] = 2,
    ACTIONS(276), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(274), 14,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1338] = 2,
    ACTIONS(280), 2,
      sym_line_break,
      anon_sym_STAR,
    ACTIONS(278), 14,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_exclamation,
      sym_question,
      sym_caret,
      sym_equal,
      sym_square_open,
      sym_text,
      sym_comment,
      sym_dinkus,
      sym_page_break,
      anon_sym__,
      anon_sym_BQUOTE,
  [1359] = 2,
    ACTIONS(340), 1,
      sym_paren_open,
    ACTIONS(262), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [1368] = 2,
    ACTIONS(342), 1,
      sym_paren_open,
    ACTIONS(268), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [1377] = 2,
    ACTIONS(344), 1,
      sym_paren_open,
    ACTIONS(256), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [1386] = 3,
    ACTIONS(346), 1,
      sym_fence_close,
    ACTIONS(348), 1,
      sym__code_line,
    STATE(61), 1,
      aux_sym_code_content_repeat1,
  [1396] = 1,
    ACTIONS(278), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [1402] = 3,
    ACTIONS(350), 1,
      sym__code_line,
    STATE(55), 1,
      aux_sym_code_content_repeat1,
    STATE(74), 1,
      sym_code_content,
  [1412] = 3,
    ACTIONS(350), 1,
      sym__code_line,
    STATE(55), 1,
      aux_sym_code_content_repeat1,
    STATE(83), 1,
      sym_code_content,
  [1422] = 1,
    ACTIONS(274), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [1428] = 1,
    ACTIONS(282), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [1434] = 3,
    ACTIONS(352), 1,
      sym_fence_close,
    ACTIONS(354), 1,
      sym__code_line,
    STATE(61), 1,
      aux_sym_code_content_repeat1,
  [1444] = 1,
    ACTIONS(302), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [1450] = 1,
    ACTIONS(290), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [1456] = 1,
    ACTIONS(298), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [1462] = 1,
    ACTIONS(294), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [1468] = 1,
    ACTIONS(306), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [1474] = 1,
    ACTIONS(286), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [1480] = 2,
    ACTIONS(357), 1,
      sym__newline,
    ACTIONS(359), 1,
      sym_code_lang,
  [1487] = 1,
    ACTIONS(361), 1,
      anon_sym_BQUOTE,
  [1491] = 1,
    ACTIONS(363), 1,
      anon_sym_BQUOTE,
  [1495] = 1,
    ACTIONS(365), 1,
      sym_square_close,
  [1499] = 1,
    ACTIONS(367), 1,
      sym_square_close,
  [1503] = 1,
    ACTIONS(369), 1,
      sym_square_close,
  [1507] = 1,
    ACTIONS(371), 1,
      sym_fence_close,
  [1511] = 1,
    ACTIONS(373), 1,
      sym_label,
  [1515] = 1,
    ACTIONS(375), 1,
      sym_label,
  [1519] = 1,
    ACTIONS(377), 1,
      sym_paren_close,
  [1523] = 1,
    ACTIONS(379), 1,
      sym_label,
  [1527] = 1,
    ACTIONS(381), 1,
      sym_paren_close,
  [1531] = 1,
    ACTIONS(383), 1,
      sym_paren_close,
  [1535] = 1,
    ACTIONS(385), 1,
      sym_resource,
  [1539] = 1,
    ACTIONS(387), 1,
      sym__newline,
  [1543] = 1,
    ACTIONS(389), 1,
      sym_fence_close,
  [1547] = 1,
    ACTIONS(391), 1,
      anon_sym_BQUOTE,
  [1551] = 1,
    ACTIONS(393), 1,
      anon_sym__,
  [1555] = 1,
    ACTIONS(395), 1,
      anon_sym_STAR,
  [1559] = 1,
    ACTIONS(397), 1,
      sym_square_close,
  [1563] = 1,
    ACTIONS(399), 1,
      sym_resource,
  [1567] = 1,
    ACTIONS(401), 1,
      sym_resource,
  [1571] = 1,
    ACTIONS(403), 1,
      sym_resource,
  [1575] = 1,
    ACTIONS(405), 1,
      sym_resource,
  [1579] = 1,
    ACTIONS(407), 1,
      sym_curly_close,
  [1583] = 1,
    ACTIONS(409), 1,
      sym_square_close,
  [1587] = 1,
    ACTIONS(411), 1,
      anon_sym_STAR,
  [1591] = 1,
    ACTIONS(413), 1,
      anon_sym__,
  [1595] = 1,
    ACTIONS(415), 1,
      ts_builtin_sym_end,
  [1599] = 1,
    ACTIONS(417), 1,
      sym_square_close,
  [1603] = 1,
    ACTIONS(419), 1,
      sym_square_close,
  [1607] = 1,
    ACTIONS(421), 1,
      sym_square_close,
  [1611] = 1,
    ACTIONS(423), 1,
      sym_square_close,
  [1615] = 1,
    ACTIONS(425), 1,
      sym_paren_close,
  [1619] = 1,
    ACTIONS(427), 1,
      sym_paren_close,
  [1623] = 1,
    ACTIONS(429), 1,
      sym_paren_close,
  [1627] = 1,
    ACTIONS(431), 1,
      sym_curly_close,
  [1631] = 1,
    ACTIONS(433), 1,
      sym_square_close,
  [1635] = 1,
    ACTIONS(435), 1,
      anon_sym_STAR,
  [1639] = 1,
    ACTIONS(437), 1,
      anon_sym__,
  [1643] = 1,
    ACTIONS(439), 1,
      sym_square_close,
  [1647] = 1,
    ACTIONS(441), 1,
      sym_square_close,
  [1651] = 1,
    ACTIONS(443), 1,
      sym_square_close,
  [1655] = 1,
    ACTIONS(445), 1,
      sym_square_close,
  [1659] = 1,
    ACTIONS(447), 1,
      sym_square_close,
  [1663] = 1,
    ACTIONS(449), 1,
      sym_paren_close,
  [1667] = 1,
    ACTIONS(451), 1,
      sym_paren_close,
  [1671] = 1,
    ACTIONS(453), 1,
      sym_paren_close,
  [1675] = 1,
    ACTIONS(455), 1,
      sym_code_inline_content,
  [1679] = 1,
    ACTIONS(457), 1,
      sym_resource,
  [1683] = 1,
    ACTIONS(459), 1,
      sym_curly_close,
  [1687] = 1,
    ACTIONS(461), 1,
      sym_square_open,
  [1691] = 1,
    ACTIONS(463), 1,
      sym_square_open,
  [1695] = 1,
    ACTIONS(465), 1,
      sym_resource,
  [1699] = 1,
    ACTIONS(467), 1,
      sym_resource,
  [1703] = 1,
    ACTIONS(469), 1,
      sym_resource,
  [1707] = 1,
    ACTIONS(471), 1,
      sym_resource,
  [1711] = 1,
    ACTIONS(473), 1,
      sym_label,
  [1715] = 1,
    ACTIONS(475), 1,
      sym_label,
  [1719] = 1,
    ACTIONS(477), 1,
      sym_label,
  [1723] = 1,
    ACTIONS(479), 1,
      sym_code_inline_content,
  [1727] = 1,
    ACTIONS(481), 1,
      sym_resource,
  [1731] = 1,
    ACTIONS(483), 1,
      sym_square_open,
  [1735] = 1,
    ACTIONS(485), 1,
      sym_square_open,
  [1739] = 1,
    ACTIONS(487), 1,
      sym_code_inline_content,
  [1743] = 1,
    ACTIONS(489), 1,
      sym_resource,
  [1747] = 1,
    ACTIONS(491), 1,
      sym_resource,
  [1751] = 1,
    ACTIONS(493), 1,
      sym_resource,
  [1755] = 1,
    ACTIONS(495), 1,
      sym_resource,
  [1759] = 1,
    ACTIONS(497), 1,
      sym_label,
  [1763] = 1,
    ACTIONS(499), 1,
      sym_label,
  [1767] = 1,
    ACTIONS(501), 1,
      sym_label,
  [1771] = 1,
    ACTIONS(503), 1,
      sym_square_open,
  [1775] = 1,
    ACTIONS(505), 1,
      sym_square_open,
  [1779] = 1,
    ACTIONS(507), 1,
      sym_square_open,
  [1783] = 1,
    ACTIONS(509), 1,
      sym_square_open,
  [1787] = 1,
    ACTIONS(511), 1,
      sym_square_open,
  [1791] = 1,
    ACTIONS(513), 1,
      sym_square_open,
  [1795] = 1,
    ACTIONS(515), 1,
      sym_square_open,
  [1799] = 1,
    ACTIONS(517), 1,
      sym_square_open,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 53,
  [SMALL_STATE(12)] = 106,
  [SMALL_STATE(13)] = 159,
  [SMALL_STATE(14)] = 211,
  [SMALL_STATE(15)] = 263,
  [SMALL_STATE(16)] = 315,
  [SMALL_STATE(17)] = 367,
  [SMALL_STATE(18)] = 419,
  [SMALL_STATE(19)] = 471,
  [SMALL_STATE(20)] = 523,
  [SMALL_STATE(21)] = 575,
  [SMALL_STATE(22)] = 627,
  [SMALL_STATE(23)] = 656,
  [SMALL_STATE(24)] = 685,
  [SMALL_STATE(25)] = 714,
  [SMALL_STATE(26)] = 740,
  [SMALL_STATE(27)] = 766,
  [SMALL_STATE(28)] = 792,
  [SMALL_STATE(29)] = 818,
  [SMALL_STATE(30)] = 844,
  [SMALL_STATE(31)] = 870,
  [SMALL_STATE(32)] = 896,
  [SMALL_STATE(33)] = 922,
  [SMALL_STATE(34)] = 948,
  [SMALL_STATE(35)] = 973,
  [SMALL_STATE(36)] = 998,
  [SMALL_STATE(37)] = 1023,
  [SMALL_STATE(38)] = 1048,
  [SMALL_STATE(39)] = 1073,
  [SMALL_STATE(40)] = 1098,
  [SMALL_STATE(41)] = 1122,
  [SMALL_STATE(42)] = 1146,
  [SMALL_STATE(43)] = 1170,
  [SMALL_STATE(44)] = 1191,
  [SMALL_STATE(45)] = 1212,
  [SMALL_STATE(46)] = 1233,
  [SMALL_STATE(47)] = 1254,
  [SMALL_STATE(48)] = 1275,
  [SMALL_STATE(49)] = 1296,
  [SMALL_STATE(50)] = 1317,
  [SMALL_STATE(51)] = 1338,
  [SMALL_STATE(52)] = 1359,
  [SMALL_STATE(53)] = 1368,
  [SMALL_STATE(54)] = 1377,
  [SMALL_STATE(55)] = 1386,
  [SMALL_STATE(56)] = 1396,
  [SMALL_STATE(57)] = 1402,
  [SMALL_STATE(58)] = 1412,
  [SMALL_STATE(59)] = 1422,
  [SMALL_STATE(60)] = 1428,
  [SMALL_STATE(61)] = 1434,
  [SMALL_STATE(62)] = 1444,
  [SMALL_STATE(63)] = 1450,
  [SMALL_STATE(64)] = 1456,
  [SMALL_STATE(65)] = 1462,
  [SMALL_STATE(66)] = 1468,
  [SMALL_STATE(67)] = 1474,
  [SMALL_STATE(68)] = 1480,
  [SMALL_STATE(69)] = 1487,
  [SMALL_STATE(70)] = 1491,
  [SMALL_STATE(71)] = 1495,
  [SMALL_STATE(72)] = 1499,
  [SMALL_STATE(73)] = 1503,
  [SMALL_STATE(74)] = 1507,
  [SMALL_STATE(75)] = 1511,
  [SMALL_STATE(76)] = 1515,
  [SMALL_STATE(77)] = 1519,
  [SMALL_STATE(78)] = 1523,
  [SMALL_STATE(79)] = 1527,
  [SMALL_STATE(80)] = 1531,
  [SMALL_STATE(81)] = 1535,
  [SMALL_STATE(82)] = 1539,
  [SMALL_STATE(83)] = 1543,
  [SMALL_STATE(84)] = 1547,
  [SMALL_STATE(85)] = 1551,
  [SMALL_STATE(86)] = 1555,
  [SMALL_STATE(87)] = 1559,
  [SMALL_STATE(88)] = 1563,
  [SMALL_STATE(89)] = 1567,
  [SMALL_STATE(90)] = 1571,
  [SMALL_STATE(91)] = 1575,
  [SMALL_STATE(92)] = 1579,
  [SMALL_STATE(93)] = 1583,
  [SMALL_STATE(94)] = 1587,
  [SMALL_STATE(95)] = 1591,
  [SMALL_STATE(96)] = 1595,
  [SMALL_STATE(97)] = 1599,
  [SMALL_STATE(98)] = 1603,
  [SMALL_STATE(99)] = 1607,
  [SMALL_STATE(100)] = 1611,
  [SMALL_STATE(101)] = 1615,
  [SMALL_STATE(102)] = 1619,
  [SMALL_STATE(103)] = 1623,
  [SMALL_STATE(104)] = 1627,
  [SMALL_STATE(105)] = 1631,
  [SMALL_STATE(106)] = 1635,
  [SMALL_STATE(107)] = 1639,
  [SMALL_STATE(108)] = 1643,
  [SMALL_STATE(109)] = 1647,
  [SMALL_STATE(110)] = 1651,
  [SMALL_STATE(111)] = 1655,
  [SMALL_STATE(112)] = 1659,
  [SMALL_STATE(113)] = 1663,
  [SMALL_STATE(114)] = 1667,
  [SMALL_STATE(115)] = 1671,
  [SMALL_STATE(116)] = 1675,
  [SMALL_STATE(117)] = 1679,
  [SMALL_STATE(118)] = 1683,
  [SMALL_STATE(119)] = 1687,
  [SMALL_STATE(120)] = 1691,
  [SMALL_STATE(121)] = 1695,
  [SMALL_STATE(122)] = 1699,
  [SMALL_STATE(123)] = 1703,
  [SMALL_STATE(124)] = 1707,
  [SMALL_STATE(125)] = 1711,
  [SMALL_STATE(126)] = 1715,
  [SMALL_STATE(127)] = 1719,
  [SMALL_STATE(128)] = 1723,
  [SMALL_STATE(129)] = 1727,
  [SMALL_STATE(130)] = 1731,
  [SMALL_STATE(131)] = 1735,
  [SMALL_STATE(132)] = 1739,
  [SMALL_STATE(133)] = 1743,
  [SMALL_STATE(134)] = 1747,
  [SMALL_STATE(135)] = 1751,
  [SMALL_STATE(136)] = 1755,
  [SMALL_STATE(137)] = 1759,
  [SMALL_STATE(138)] = 1763,
  [SMALL_STATE(139)] = 1767,
  [SMALL_STATE(140)] = 1771,
  [SMALL_STATE(141)] = 1775,
  [SMALL_STATE(142)] = 1779,
  [SMALL_STATE(143)] = 1783,
  [SMALL_STATE(144)] = 1787,
  [SMALL_STATE(145)] = 1791,
  [SMALL_STATE(146)] = 1795,
  [SMALL_STATE(147)] = 1799,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(4),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(4),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(20),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(21),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(14),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(10),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(11),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(12),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(68),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(132),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(131),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(130),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(120),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(119),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(81),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(5),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(5),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(20),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(21),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(14),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(132),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(131),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(130),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(120),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(119),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(81),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(9),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(9),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(19),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(18),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(17),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(116),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(140),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(141),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(142),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(143),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(117),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_view, 4),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_view, 4),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_inline, 3),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_inline, 3),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 3),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 3),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 3),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold, 3),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_monospaced, 3),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_monospaced, 3),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_view_label, 7),
  [288] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_view_label, 7),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_footnote_ref, 4),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_footnote_ref, 4),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_inline_lang, 6),
  [296] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_inline_lang, 6),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_footnote_desc, 4),
  [300] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_footnote_desc, 4),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 4),
  [304] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 4),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_label, 6),
  [308] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link_label, 6),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 4),
  [312] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 4),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2),
  [316] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chapter, 3),
  [320] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_chapter, 3),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3),
  [324] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subsection, 3),
  [328] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subsection, 3),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block_lang, 5),
  [332] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block_lang, 5),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_content, 1),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_content_repeat1, 2),
  [354] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_content_repeat1, 2), SHIFT_REPEAT(61),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [415] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [431] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [435] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [437] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [439] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [441] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [443] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [445] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [447] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [449] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [451] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [453] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [455] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [457] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [459] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [461] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [463] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [465] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [467] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [469] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [471] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [473] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [475] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [477] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [479] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [481] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [483] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [485] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [487] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [489] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [491] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [493] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [495] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [497] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [499] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [501] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [503] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [505] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [507] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [509] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [511] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [513] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [515] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [517] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_gularen_external_scanner_create(void);
void tree_sitter_gularen_external_scanner_destroy(void *);
bool tree_sitter_gularen_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_gularen_external_scanner_serialize(void *, char *);
void tree_sitter_gularen_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_gularen(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_gularen_external_scanner_create,
      tree_sitter_gularen_external_scanner_destroy,
      tree_sitter_gularen_external_scanner_scan,
      tree_sitter_gularen_external_scanner_serialize,
      tree_sitter_gularen_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
