#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 73
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 16
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  sym_comment = 1,
  anon_sym_STAR = 2,
  anon_sym__ = 3,
  anon_sym_BQUOTE = 4,
  sym__newline = 5,
  sym__newline_plus = 6,
  sym_head3 = 7,
  sym_head2 = 8,
  sym_head1 = 9,
  sym_fence_open = 10,
  sym_fence_close = 11,
  sym_code_lang = 12,
  sym__code_line = 13,
  sym_curly_open = 14,
  sym_curly_close = 15,
  sym_code_inline_content = 16,
  sym_paren_open = 17,
  sym_paren_close = 18,
  sym_label = 19,
  sym_text = 20,
  sym_document = 21,
  sym__block = 22,
  sym_chapter = 23,
  sym_section = 24,
  sym_subsection = 25,
  sym_code_block_lang = 26,
  sym_code_block = 27,
  sym_code_content = 28,
  sym_paragraph = 29,
  sym__end_block = 30,
  sym__inline = 31,
  sym_bold = 32,
  sym_italic = 33,
  sym_monospaced = 34,
  sym_code_inline_lang = 35,
  sym_code_inline = 36,
  aux_sym_document_repeat1 = 37,
  aux_sym_chapter_repeat1 = 38,
  aux_sym_code_content_repeat1 = 39,
  aux_sym_paragraph_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [anon_sym_BQUOTE] = "`",
  [sym__newline] = "_newline",
  [sym__newline_plus] = "_newline_plus",
  [sym_head3] = "head3",
  [sym_head2] = "head2",
  [sym_head1] = "head1",
  [sym_fence_open] = "fence_open",
  [sym_fence_close] = "fence_close",
  [sym_code_lang] = "code_lang",
  [sym__code_line] = "_code_line",
  [sym_curly_open] = "curly_open",
  [sym_curly_close] = "curly_close",
  [sym_code_inline_content] = "code_inline_content",
  [sym_paren_open] = "paren_open",
  [sym_paren_close] = "paren_close",
  [sym_label] = "label",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_chapter] = "chapter",
  [sym_section] = "section",
  [sym_subsection] = "subsection",
  [sym_code_block_lang] = "code_block_lang",
  [sym_code_block] = "code_block",
  [sym_code_content] = "code_content",
  [sym_paragraph] = "paragraph",
  [sym__end_block] = "_end_block",
  [sym__inline] = "_inline",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [sym_monospaced] = "monospaced",
  [sym_code_inline_lang] = "code_inline_lang",
  [sym_code_inline] = "code_inline",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_chapter_repeat1] = "chapter_repeat1",
  [aux_sym_code_content_repeat1] = "code_content_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [sym__newline] = sym__newline,
  [sym__newline_plus] = sym__newline_plus,
  [sym_head3] = sym_head3,
  [sym_head2] = sym_head2,
  [sym_head1] = sym_head1,
  [sym_fence_open] = sym_fence_open,
  [sym_fence_close] = sym_fence_close,
  [sym_code_lang] = sym_code_lang,
  [sym__code_line] = sym__code_line,
  [sym_curly_open] = sym_curly_open,
  [sym_curly_close] = sym_curly_close,
  [sym_code_inline_content] = sym_code_inline_content,
  [sym_paren_open] = sym_paren_open,
  [sym_paren_close] = sym_paren_close,
  [sym_label] = sym_label,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_chapter] = sym_chapter,
  [sym_section] = sym_section,
  [sym_subsection] = sym_subsection,
  [sym_code_block_lang] = sym_code_block_lang,
  [sym_code_block] = sym_code_block,
  [sym_code_content] = sym_code_content,
  [sym_paragraph] = sym_paragraph,
  [sym__end_block] = sym__end_block,
  [sym__inline] = sym__inline,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [sym_monospaced] = sym_monospaced,
  [sym_code_inline_lang] = sym_code_inline_lang,
  [sym_code_inline] = sym_code_inline,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_chapter_repeat1] = aux_sym_chapter_repeat1,
  [aux_sym_code_content_repeat1] = aux_sym_code_content_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__newline_plus] = {
    .visible = false,
    .named = true,
  },
  [sym_head3] = {
    .visible = true,
    .named = true,
  },
  [sym_head2] = {
    .visible = true,
    .named = true,
  },
  [sym_head1] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_open] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_close] = {
    .visible = true,
    .named = true,
  },
  [sym_code_lang] = {
    .visible = true,
    .named = true,
  },
  [sym__code_line] = {
    .visible = false,
    .named = true,
  },
  [sym_curly_open] = {
    .visible = true,
    .named = true,
  },
  [sym_curly_close] = {
    .visible = true,
    .named = true,
  },
  [sym_code_inline_content] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_open] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_close] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_chapter] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_subsection] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block_lang] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_code_content] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym__end_block] = {
    .visible = false,
    .named = true,
  },
  [sym__inline] = {
    .visible = false,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_monospaced] = {
    .visible = true,
    .named = true,
  },
  [sym_code_inline_lang] = {
    .visible = true,
    .named = true,
  },
  [sym_code_inline] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chapter_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 19,
  [25] = 25,
  [26] = 22,
  [27] = 27,
  [28] = 28,
  [29] = 22,
  [30] = 30,
  [31] = 25,
  [32] = 25,
  [33] = 10,
  [34] = 15,
  [35] = 16,
  [36] = 11,
  [37] = 13,
  [38] = 10,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 11,
  [44] = 13,
  [45] = 15,
  [46] = 16,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 48,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 49,
  [58] = 48,
  [59] = 54,
  [60] = 55,
  [61] = 56,
  [62] = 49,
  [63] = 51,
  [64] = 64,
  [65] = 56,
  [66] = 55,
  [67] = 50,
  [68] = 51,
  [69] = 54,
  [70] = 70,
  [71] = 71,
  [72] = 50,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == '`') ADVANCE(5);
      if (lookahead == '~') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 4},
  [7] = {.lex_state = 0, .external_lex_state = 4},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0, .external_lex_state = 4},
  [10] = {.lex_state = 0, .external_lex_state = 5},
  [11] = {.lex_state = 0, .external_lex_state = 3},
  [12] = {.lex_state = 0, .external_lex_state = 6},
  [13] = {.lex_state = 0, .external_lex_state = 3},
  [14] = {.lex_state = 0, .external_lex_state = 6},
  [15] = {.lex_state = 0, .external_lex_state = 3},
  [16] = {.lex_state = 0, .external_lex_state = 3},
  [17] = {.lex_state = 0, .external_lex_state = 6},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 6},
  [20] = {.lex_state = 0, .external_lex_state = 6},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 6},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 6},
  [25] = {.lex_state = 0, .external_lex_state = 6},
  [26] = {.lex_state = 0, .external_lex_state = 6},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 6},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 6},
  [32] = {.lex_state = 0, .external_lex_state = 6},
  [33] = {.lex_state = 0, .external_lex_state = 7},
  [34] = {.lex_state = 0, .external_lex_state = 4},
  [35] = {.lex_state = 0, .external_lex_state = 4},
  [36] = {.lex_state = 0, .external_lex_state = 4},
  [37] = {.lex_state = 0, .external_lex_state = 4},
  [38] = {.lex_state = 0, .external_lex_state = 8},
  [39] = {.lex_state = 0, .external_lex_state = 9},
  [40] = {.lex_state = 0, .external_lex_state = 9},
  [41] = {.lex_state = 0, .external_lex_state = 10},
  [42] = {.lex_state = 0, .external_lex_state = 10},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0, .external_lex_state = 11},
  [48] = {.lex_state = 0, .external_lex_state = 12},
  [49] = {.lex_state = 0, .external_lex_state = 13},
  [50] = {.lex_state = 0, .external_lex_state = 14},
  [51] = {.lex_state = 0, .external_lex_state = 15},
  [52] = {.lex_state = 0, .external_lex_state = 16},
  [53] = {.lex_state = 0, .external_lex_state = 12},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0, .external_lex_state = 13},
  [58] = {.lex_state = 0, .external_lex_state = 12},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0, .external_lex_state = 13},
  [63] = {.lex_state = 0, .external_lex_state = 15},
  [64] = {.lex_state = 0, .external_lex_state = 16},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0, .external_lex_state = 14},
  [68] = {.lex_state = 0, .external_lex_state = 15},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0, .external_lex_state = 17},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0, .external_lex_state = 14},
};

enum {
  ts_external_token__newline = 0,
  ts_external_token__newline_plus = 1,
  ts_external_token_head3 = 2,
  ts_external_token_head2 = 3,
  ts_external_token_head1 = 4,
  ts_external_token_fence_open = 5,
  ts_external_token_fence_close = 6,
  ts_external_token_code_lang = 7,
  ts_external_token__code_line = 8,
  ts_external_token_curly_open = 9,
  ts_external_token_curly_close = 10,
  ts_external_token_code_inline_content = 11,
  ts_external_token_paren_open = 12,
  ts_external_token_paren_close = 13,
  ts_external_token_label = 14,
  ts_external_token_text = 15,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__newline_plus] = sym__newline_plus,
  [ts_external_token_head3] = sym_head3,
  [ts_external_token_head2] = sym_head2,
  [ts_external_token_head1] = sym_head1,
  [ts_external_token_fence_open] = sym_fence_open,
  [ts_external_token_fence_close] = sym_fence_close,
  [ts_external_token_code_lang] = sym_code_lang,
  [ts_external_token__code_line] = sym__code_line,
  [ts_external_token_curly_open] = sym_curly_open,
  [ts_external_token_curly_close] = sym_curly_close,
  [ts_external_token_code_inline_content] = sym_code_inline_content,
  [ts_external_token_paren_open] = sym_paren_open,
  [ts_external_token_paren_close] = sym_paren_close,
  [ts_external_token_label] = sym_label,
  [ts_external_token_text] = sym_text,
};

static const bool ts_external_scanner_states[18][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_head3] = true,
    [ts_external_token_head2] = true,
    [ts_external_token_head1] = true,
    [ts_external_token_fence_open] = true,
    [ts_external_token_fence_close] = true,
    [ts_external_token_code_lang] = true,
    [ts_external_token__code_line] = true,
    [ts_external_token_curly_open] = true,
    [ts_external_token_curly_close] = true,
    [ts_external_token_code_inline_content] = true,
    [ts_external_token_paren_open] = true,
    [ts_external_token_paren_close] = true,
    [ts_external_token_label] = true,
    [ts_external_token_text] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token_head3] = true,
    [ts_external_token_head2] = true,
    [ts_external_token_head1] = true,
    [ts_external_token_fence_open] = true,
    [ts_external_token_curly_open] = true,
    [ts_external_token_text] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_head3] = true,
    [ts_external_token_head2] = true,
    [ts_external_token_head1] = true,
    [ts_external_token_fence_open] = true,
    [ts_external_token_curly_open] = true,
    [ts_external_token_text] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_curly_open] = true,
    [ts_external_token_text] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_head3] = true,
    [ts_external_token_head2] = true,
    [ts_external_token_head1] = true,
    [ts_external_token_fence_open] = true,
    [ts_external_token_curly_open] = true,
    [ts_external_token_paren_open] = true,
    [ts_external_token_text] = true,
  },
  [6] = {
    [ts_external_token_curly_open] = true,
    [ts_external_token_text] = true,
  },
  [7] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_curly_open] = true,
    [ts_external_token_paren_open] = true,
    [ts_external_token_text] = true,
  },
  [8] = {
    [ts_external_token_paren_open] = true,
  },
  [9] = {
    [ts_external_token__code_line] = true,
  },
  [10] = {
    [ts_external_token_fence_close] = true,
    [ts_external_token__code_line] = true,
  },
  [11] = {
    [ts_external_token__newline] = true,
    [ts_external_token_code_lang] = true,
  },
  [12] = {
    [ts_external_token_curly_close] = true,
  },
  [13] = {
    [ts_external_token_paren_close] = true,
  },
  [14] = {
    [ts_external_token_label] = true,
  },
  [15] = {
    [ts_external_token_code_inline_content] = true,
  },
  [16] = {
    [ts_external_token_fence_close] = true,
  },
  [17] = {
    [ts_external_token__newline] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__newline_plus] = ACTIONS(1),
    [sym_head3] = ACTIONS(1),
    [sym_head2] = ACTIONS(1),
    [sym_head1] = ACTIONS(1),
    [sym_fence_open] = ACTIONS(1),
    [sym_fence_close] = ACTIONS(1),
    [sym_code_lang] = ACTIONS(1),
    [sym__code_line] = ACTIONS(1),
    [sym_curly_open] = ACTIONS(1),
    [sym_curly_close] = ACTIONS(1),
    [sym_code_inline_content] = ACTIONS(1),
    [sym_paren_open] = ACTIONS(1),
    [sym_paren_close] = ACTIONS(1),
    [sym_label] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(71),
    [sym__block] = STATE(2),
    [sym_chapter] = STATE(2),
    [sym_section] = STATE(2),
    [sym_subsection] = STATE(2),
    [sym_code_block_lang] = STATE(2),
    [sym_code_block] = STATE(2),
    [sym_paragraph] = STATE(2),
    [sym__inline] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_monospaced] = STATE(5),
    [sym_code_inline_lang] = STATE(5),
    [sym_code_inline] = STATE(5),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [sym__newline] = ACTIONS(5),
    [sym_head3] = ACTIONS(13),
    [sym_head2] = ACTIONS(15),
    [sym_head1] = ACTIONS(17),
    [sym_fence_open] = ACTIONS(19),
    [sym_curly_open] = ACTIONS(21),
    [sym_text] = ACTIONS(5),
  },
  [2] = {
    [sym__block] = STATE(3),
    [sym_chapter] = STATE(3),
    [sym_section] = STATE(3),
    [sym_subsection] = STATE(3),
    [sym_code_block_lang] = STATE(3),
    [sym_code_block] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym__inline] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_monospaced] = STATE(5),
    [sym_code_inline_lang] = STATE(5),
    [sym_code_inline] = STATE(5),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_comment] = ACTIONS(5),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [sym__newline] = ACTIONS(5),
    [sym_head3] = ACTIONS(13),
    [sym_head2] = ACTIONS(15),
    [sym_head1] = ACTIONS(17),
    [sym_fence_open] = ACTIONS(19),
    [sym_curly_open] = ACTIONS(21),
    [sym_text] = ACTIONS(5),
  },
  [3] = {
    [sym__block] = STATE(3),
    [sym_chapter] = STATE(3),
    [sym_section] = STATE(3),
    [sym_subsection] = STATE(3),
    [sym_code_block_lang] = STATE(3),
    [sym_code_block] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym__inline] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_monospaced] = STATE(5),
    [sym_code_inline_lang] = STATE(5),
    [sym_code_inline] = STATE(5),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_comment] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(30),
    [anon_sym__] = ACTIONS(33),
    [anon_sym_BQUOTE] = ACTIONS(36),
    [sym__newline] = ACTIONS(27),
    [sym_head3] = ACTIONS(39),
    [sym_head2] = ACTIONS(42),
    [sym_head1] = ACTIONS(45),
    [sym_fence_open] = ACTIONS(48),
    [sym_curly_open] = ACTIONS(51),
    [sym_text] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(59), 1,
      anon_sym_STAR,
    ACTIONS(62), 1,
      anon_sym__,
    ACTIONS(65), 1,
      anon_sym_BQUOTE,
    ACTIONS(68), 1,
      sym_curly_open,
    ACTIONS(56), 3,
      sym__newline,
      sym_text,
      sym_comment,
    ACTIONS(54), 6,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      ts_builtin_sym_end,
    STATE(4), 7,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
      aux_sym_paragraph_repeat1,
  [35] = 8,
    ACTIONS(7), 1,
      anon_sym_STAR,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      anon_sym_BQUOTE,
    ACTIONS(21), 1,
      sym_curly_open,
    ACTIONS(75), 1,
      sym__newline_plus,
    ACTIONS(73), 3,
      sym__newline,
      sym_text,
      sym_comment,
    ACTIONS(71), 5,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      ts_builtin_sym_end,
    STATE(4), 7,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
      aux_sym_paragraph_repeat1,
  [72] = 8,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(81), 1,
      anon_sym__,
    ACTIONS(83), 1,
      anon_sym_BQUOTE,
    ACTIONS(87), 1,
      sym_curly_open,
    STATE(28), 1,
      sym__end_block,
    ACTIONS(77), 2,
      sym_text,
      sym_comment,
    ACTIONS(85), 2,
      sym__newline,
      sym__newline_plus,
    STATE(9), 7,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
      aux_sym_chapter_repeat1,
  [105] = 8,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(81), 1,
      anon_sym__,
    ACTIONS(83), 1,
      anon_sym_BQUOTE,
    ACTIONS(87), 1,
      sym_curly_open,
    STATE(21), 1,
      sym__end_block,
    ACTIONS(77), 2,
      sym_text,
      sym_comment,
    ACTIONS(89), 2,
      sym__newline,
      sym__newline_plus,
    STATE(9), 7,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
      aux_sym_chapter_repeat1,
  [138] = 8,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(81), 1,
      anon_sym__,
    ACTIONS(83), 1,
      anon_sym_BQUOTE,
    ACTIONS(87), 1,
      sym_curly_open,
    STATE(27), 1,
      sym__end_block,
    ACTIONS(77), 2,
      sym_text,
      sym_comment,
    ACTIONS(91), 2,
      sym__newline,
      sym__newline_plus,
    STATE(9), 7,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
      aux_sym_chapter_repeat1,
  [171] = 7,
    ACTIONS(96), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym__,
    ACTIONS(102), 1,
      anon_sym_BQUOTE,
    ACTIONS(107), 1,
      sym_curly_open,
    ACTIONS(93), 2,
      sym_text,
      sym_comment,
    ACTIONS(105), 2,
      sym__newline,
      sym__newline_plus,
    STATE(9), 7,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
      aux_sym_chapter_repeat1,
  [201] = 2,
    ACTIONS(112), 1,
      sym_paren_open,
    ACTIONS(110), 13,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [220] = 1,
    ACTIONS(114), 13,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [236] = 6,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(81), 1,
      anon_sym__,
    ACTIONS(83), 1,
      anon_sym_BQUOTE,
    ACTIONS(87), 1,
      sym_curly_open,
    ACTIONS(116), 2,
      sym_text,
      sym_comment,
    STATE(7), 7,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
      aux_sym_chapter_repeat1,
  [262] = 1,
    ACTIONS(118), 13,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [278] = 6,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(81), 1,
      anon_sym__,
    ACTIONS(83), 1,
      anon_sym_BQUOTE,
    ACTIONS(87), 1,
      sym_curly_open,
    ACTIONS(120), 2,
      sym_text,
      sym_comment,
    STATE(6), 7,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
      aux_sym_chapter_repeat1,
  [304] = 1,
    ACTIONS(122), 13,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [320] = 1,
    ACTIONS(124), 13,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [336] = 6,
    ACTIONS(79), 1,
      anon_sym_STAR,
    ACTIONS(81), 1,
      anon_sym__,
    ACTIONS(83), 1,
      anon_sym_BQUOTE,
    ACTIONS(87), 1,
      sym_curly_open,
    ACTIONS(126), 2,
      sym_text,
      sym_comment,
    STATE(8), 7,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
      aux_sym_chapter_repeat1,
  [362] = 1,
    ACTIONS(128), 12,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [377] = 6,
    ACTIONS(132), 1,
      anon_sym_STAR,
    ACTIONS(134), 1,
      anon_sym__,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    ACTIONS(138), 1,
      sym_curly_open,
    ACTIONS(130), 2,
      sym_text,
      sym_comment,
    STATE(65), 6,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
  [402] = 6,
    ACTIONS(132), 1,
      anon_sym_STAR,
    ACTIONS(134), 1,
      anon_sym__,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    ACTIONS(138), 1,
      sym_curly_open,
    ACTIONS(140), 2,
      sym_text,
      sym_comment,
    STATE(56), 6,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
  [427] = 1,
    ACTIONS(142), 12,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [442] = 6,
    ACTIONS(132), 1,
      anon_sym_STAR,
    ACTIONS(134), 1,
      anon_sym__,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    ACTIONS(138), 1,
      sym_curly_open,
    ACTIONS(144), 2,
      sym_text,
      sym_comment,
    STATE(54), 6,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
  [467] = 1,
    ACTIONS(146), 12,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [482] = 6,
    ACTIONS(132), 1,
      anon_sym_STAR,
    ACTIONS(134), 1,
      anon_sym__,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    ACTIONS(138), 1,
      sym_curly_open,
    ACTIONS(148), 2,
      sym_text,
      sym_comment,
    STATE(61), 6,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
  [507] = 6,
    ACTIONS(132), 1,
      anon_sym_STAR,
    ACTIONS(134), 1,
      anon_sym__,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    ACTIONS(138), 1,
      sym_curly_open,
    ACTIONS(150), 2,
      sym_text,
      sym_comment,
    STATE(55), 6,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
  [532] = 6,
    ACTIONS(132), 1,
      anon_sym_STAR,
    ACTIONS(134), 1,
      anon_sym__,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    ACTIONS(138), 1,
      sym_curly_open,
    ACTIONS(152), 2,
      sym_text,
      sym_comment,
    STATE(59), 6,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
  [557] = 1,
    ACTIONS(154), 12,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [572] = 1,
    ACTIONS(156), 12,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [587] = 6,
    ACTIONS(132), 1,
      anon_sym_STAR,
    ACTIONS(134), 1,
      anon_sym__,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    ACTIONS(138), 1,
      sym_curly_open,
    ACTIONS(158), 2,
      sym_text,
      sym_comment,
    STATE(69), 6,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
  [612] = 1,
    ACTIONS(160), 12,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_curly_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [627] = 6,
    ACTIONS(132), 1,
      anon_sym_STAR,
    ACTIONS(134), 1,
      anon_sym__,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    ACTIONS(138), 1,
      sym_curly_open,
    ACTIONS(162), 2,
      sym_text,
      sym_comment,
    STATE(60), 6,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
  [652] = 6,
    ACTIONS(132), 1,
      anon_sym_STAR,
    ACTIONS(134), 1,
      anon_sym__,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    ACTIONS(138), 1,
      sym_curly_open,
    ACTIONS(164), 2,
      sym_text,
      sym_comment,
    STATE(66), 6,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      sym_code_inline_lang,
      sym_code_inline,
  [677] = 2,
    ACTIONS(166), 1,
      sym_paren_open,
    ACTIONS(110), 8,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_text,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [691] = 1,
    ACTIONS(122), 8,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_text,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [702] = 1,
    ACTIONS(124), 8,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_text,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [713] = 1,
    ACTIONS(114), 8,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_text,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [724] = 1,
    ACTIONS(118), 8,
      sym__newline,
      sym__newline_plus,
      sym_curly_open,
      sym_text,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [735] = 2,
    ACTIONS(168), 1,
      sym_paren_open,
    ACTIONS(110), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [744] = 3,
    ACTIONS(170), 1,
      sym__code_line,
    STATE(41), 1,
      aux_sym_code_content_repeat1,
    STATE(64), 1,
      sym_code_content,
  [754] = 3,
    ACTIONS(170), 1,
      sym__code_line,
    STATE(41), 1,
      aux_sym_code_content_repeat1,
    STATE(52), 1,
      sym_code_content,
  [764] = 3,
    ACTIONS(172), 1,
      sym_fence_close,
    ACTIONS(174), 1,
      sym__code_line,
    STATE(42), 1,
      aux_sym_code_content_repeat1,
  [774] = 3,
    ACTIONS(176), 1,
      sym_fence_close,
    ACTIONS(178), 1,
      sym__code_line,
    STATE(42), 1,
      aux_sym_code_content_repeat1,
  [784] = 1,
    ACTIONS(114), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [790] = 1,
    ACTIONS(118), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [796] = 1,
    ACTIONS(122), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [802] = 1,
    ACTIONS(124), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [808] = 2,
    ACTIONS(181), 1,
      sym__newline,
    ACTIONS(183), 1,
      sym_code_lang,
  [815] = 1,
    ACTIONS(185), 1,
      sym_curly_close,
  [819] = 1,
    ACTIONS(187), 1,
      sym_paren_close,
  [823] = 1,
    ACTIONS(189), 1,
      sym_label,
  [827] = 1,
    ACTIONS(191), 1,
      sym_code_inline_content,
  [831] = 1,
    ACTIONS(193), 1,
      sym_fence_close,
  [835] = 1,
    ACTIONS(195), 1,
      sym_curly_close,
  [839] = 1,
    ACTIONS(197), 1,
      anon_sym_STAR,
  [843] = 1,
    ACTIONS(199), 1,
      anon_sym__,
  [847] = 1,
    ACTIONS(201), 1,
      anon_sym_BQUOTE,
  [851] = 1,
    ACTIONS(203), 1,
      sym_paren_close,
  [855] = 1,
    ACTIONS(205), 1,
      sym_curly_close,
  [859] = 1,
    ACTIONS(207), 1,
      anon_sym_STAR,
  [863] = 1,
    ACTIONS(209), 1,
      anon_sym__,
  [867] = 1,
    ACTIONS(211), 1,
      anon_sym_BQUOTE,
  [871] = 1,
    ACTIONS(213), 1,
      sym_paren_close,
  [875] = 1,
    ACTIONS(215), 1,
      sym_code_inline_content,
  [879] = 1,
    ACTIONS(217), 1,
      sym_fence_close,
  [883] = 1,
    ACTIONS(219), 1,
      anon_sym_BQUOTE,
  [887] = 1,
    ACTIONS(221), 1,
      anon_sym__,
  [891] = 1,
    ACTIONS(223), 1,
      sym_label,
  [895] = 1,
    ACTIONS(225), 1,
      sym_code_inline_content,
  [899] = 1,
    ACTIONS(227), 1,
      anon_sym_STAR,
  [903] = 1,
    ACTIONS(229), 1,
      sym__newline,
  [907] = 1,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
  [911] = 1,
    ACTIONS(233), 1,
      sym_label,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 35,
  [SMALL_STATE(6)] = 72,
  [SMALL_STATE(7)] = 105,
  [SMALL_STATE(8)] = 138,
  [SMALL_STATE(9)] = 171,
  [SMALL_STATE(10)] = 201,
  [SMALL_STATE(11)] = 220,
  [SMALL_STATE(12)] = 236,
  [SMALL_STATE(13)] = 262,
  [SMALL_STATE(14)] = 278,
  [SMALL_STATE(15)] = 304,
  [SMALL_STATE(16)] = 320,
  [SMALL_STATE(17)] = 336,
  [SMALL_STATE(18)] = 362,
  [SMALL_STATE(19)] = 377,
  [SMALL_STATE(20)] = 402,
  [SMALL_STATE(21)] = 427,
  [SMALL_STATE(22)] = 442,
  [SMALL_STATE(23)] = 467,
  [SMALL_STATE(24)] = 482,
  [SMALL_STATE(25)] = 507,
  [SMALL_STATE(26)] = 532,
  [SMALL_STATE(27)] = 557,
  [SMALL_STATE(28)] = 572,
  [SMALL_STATE(29)] = 587,
  [SMALL_STATE(30)] = 612,
  [SMALL_STATE(31)] = 627,
  [SMALL_STATE(32)] = 652,
  [SMALL_STATE(33)] = 677,
  [SMALL_STATE(34)] = 691,
  [SMALL_STATE(35)] = 702,
  [SMALL_STATE(36)] = 713,
  [SMALL_STATE(37)] = 724,
  [SMALL_STATE(38)] = 735,
  [SMALL_STATE(39)] = 744,
  [SMALL_STATE(40)] = 754,
  [SMALL_STATE(41)] = 764,
  [SMALL_STATE(42)] = 774,
  [SMALL_STATE(43)] = 784,
  [SMALL_STATE(44)] = 790,
  [SMALL_STATE(45)] = 796,
  [SMALL_STATE(46)] = 802,
  [SMALL_STATE(47)] = 808,
  [SMALL_STATE(48)] = 815,
  [SMALL_STATE(49)] = 819,
  [SMALL_STATE(50)] = 823,
  [SMALL_STATE(51)] = 827,
  [SMALL_STATE(52)] = 831,
  [SMALL_STATE(53)] = 835,
  [SMALL_STATE(54)] = 839,
  [SMALL_STATE(55)] = 843,
  [SMALL_STATE(56)] = 847,
  [SMALL_STATE(57)] = 851,
  [SMALL_STATE(58)] = 855,
  [SMALL_STATE(59)] = 859,
  [SMALL_STATE(60)] = 863,
  [SMALL_STATE(61)] = 867,
  [SMALL_STATE(62)] = 871,
  [SMALL_STATE(63)] = 875,
  [SMALL_STATE(64)] = 879,
  [SMALL_STATE(65)] = 883,
  [SMALL_STATE(66)] = 887,
  [SMALL_STATE(67)] = 891,
  [SMALL_STATE(68)] = 895,
  [SMALL_STATE(69)] = 899,
  [SMALL_STATE(70)] = 903,
  [SMALL_STATE(71)] = 907,
  [SMALL_STATE(72)] = 911,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(5),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(29),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(32),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(19),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(12),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(17),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(14),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(47),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(51),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(4),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(29),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(32),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(19),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(51),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(9),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(22),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(25),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(20),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(63),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_inline, 3),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_monospaced, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_inline_lang, 6),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block_lang, 5),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chapter, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subsection, 3),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 4),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_content, 1),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_content_repeat1, 2),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_content_repeat1, 2), SHIFT_REPEAT(42),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [231] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_gularen_external_scanner_create(void);
void tree_sitter_gularen_external_scanner_destroy(void *);
bool tree_sitter_gularen_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_gularen_external_scanner_serialize(void *, char *);
void tree_sitter_gularen_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_gularen(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_gularen_external_scanner_create,
      tree_sitter_gularen_external_scanner_destroy,
      tree_sitter_gularen_external_scanner_scan,
      tree_sitter_gularen_external_scanner_serialize,
      tree_sitter_gularen_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
