#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 55
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  sym_comment = 1,
  anon_sym_STAR = 2,
  anon_sym__ = 3,
  anon_sym_BQUOTE = 4,
  sym__newline = 5,
  sym__newline_plus = 6,
  sym_head3 = 7,
  sym_head2 = 8,
  sym_head1 = 9,
  sym_fence_open = 10,
  sym_fence_close = 11,
  sym_code_lang = 12,
  sym__code_line = 13,
  sym_text = 14,
  sym_document = 15,
  sym__block = 16,
  sym_chapter = 17,
  sym_section = 18,
  sym_subsection = 19,
  sym_code_block_lang = 20,
  sym_code_block = 21,
  sym_code_content = 22,
  sym_paragraph = 23,
  sym__end_block = 24,
  sym__inline = 25,
  sym_bold = 26,
  sym_italic = 27,
  sym_monospaced = 28,
  aux_sym_document_repeat1 = 29,
  aux_sym_chapter_repeat1 = 30,
  aux_sym_code_content_repeat1 = 31,
  aux_sym_paragraph_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [anon_sym_BQUOTE] = "`",
  [sym__newline] = "_newline",
  [sym__newline_plus] = "_newline_plus",
  [sym_head3] = "head3",
  [sym_head2] = "head2",
  [sym_head1] = "head1",
  [sym_fence_open] = "fence_open",
  [sym_fence_close] = "fence_close",
  [sym_code_lang] = "code_lang",
  [sym__code_line] = "_code_line",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_chapter] = "chapter",
  [sym_section] = "section",
  [sym_subsection] = "subsection",
  [sym_code_block_lang] = "code_block_lang",
  [sym_code_block] = "code_block",
  [sym_code_content] = "code_content",
  [sym_paragraph] = "paragraph",
  [sym__end_block] = "_end_block",
  [sym__inline] = "_inline",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [sym_monospaced] = "monospaced",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_chapter_repeat1] = "chapter_repeat1",
  [aux_sym_code_content_repeat1] = "code_content_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [sym__newline] = sym__newline,
  [sym__newline_plus] = sym__newline_plus,
  [sym_head3] = sym_head3,
  [sym_head2] = sym_head2,
  [sym_head1] = sym_head1,
  [sym_fence_open] = sym_fence_open,
  [sym_fence_close] = sym_fence_close,
  [sym_code_lang] = sym_code_lang,
  [sym__code_line] = sym__code_line,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_chapter] = sym_chapter,
  [sym_section] = sym_section,
  [sym_subsection] = sym_subsection,
  [sym_code_block_lang] = sym_code_block_lang,
  [sym_code_block] = sym_code_block,
  [sym_code_content] = sym_code_content,
  [sym_paragraph] = sym_paragraph,
  [sym__end_block] = sym__end_block,
  [sym__inline] = sym__inline,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [sym_monospaced] = sym_monospaced,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_chapter_repeat1] = aux_sym_chapter_repeat1,
  [aux_sym_code_content_repeat1] = aux_sym_code_content_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__newline_plus] = {
    .visible = false,
    .named = true,
  },
  [sym_head3] = {
    .visible = true,
    .named = true,
  },
  [sym_head2] = {
    .visible = true,
    .named = true,
  },
  [sym_head1] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_open] = {
    .visible = true,
    .named = true,
  },
  [sym_fence_close] = {
    .visible = true,
    .named = true,
  },
  [sym_code_lang] = {
    .visible = true,
    .named = true,
  },
  [sym__code_line] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_chapter] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_subsection] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block_lang] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_code_content] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym__end_block] = {
    .visible = false,
    .named = true,
  },
  [sym__inline] = {
    .visible = false,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_monospaced] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chapter_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 22,
  [26] = 23,
  [27] = 24,
  [28] = 22,
  [29] = 23,
  [30] = 24,
  [31] = 9,
  [32] = 10,
  [33] = 11,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 11,
  [38] = 10,
  [39] = 9,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 44,
  [48] = 45,
  [49] = 46,
  [50] = 50,
  [51] = 46,
  [52] = 45,
  [53] = 44,
  [54] = 54,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == '`') ADVANCE(5);
      if (lookahead == '~') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 4},
  [7] = {.lex_state = 0, .external_lex_state = 4},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0, .external_lex_state = 3},
  [10] = {.lex_state = 0, .external_lex_state = 3},
  [11] = {.lex_state = 0, .external_lex_state = 3},
  [12] = {.lex_state = 0, .external_lex_state = 4},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 5},
  [20] = {.lex_state = 0, .external_lex_state = 5},
  [21] = {.lex_state = 0, .external_lex_state = 5},
  [22] = {.lex_state = 0, .external_lex_state = 5},
  [23] = {.lex_state = 0, .external_lex_state = 5},
  [24] = {.lex_state = 0, .external_lex_state = 5},
  [25] = {.lex_state = 0, .external_lex_state = 5},
  [26] = {.lex_state = 0, .external_lex_state = 5},
  [27] = {.lex_state = 0, .external_lex_state = 5},
  [28] = {.lex_state = 0, .external_lex_state = 5},
  [29] = {.lex_state = 0, .external_lex_state = 5},
  [30] = {.lex_state = 0, .external_lex_state = 5},
  [31] = {.lex_state = 0, .external_lex_state = 4},
  [32] = {.lex_state = 0, .external_lex_state = 4},
  [33] = {.lex_state = 0, .external_lex_state = 4},
  [34] = {.lex_state = 0, .external_lex_state = 6},
  [35] = {.lex_state = 0, .external_lex_state = 7},
  [36] = {.lex_state = 0, .external_lex_state = 6},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0, .external_lex_state = 7},
  [41] = {.lex_state = 0, .external_lex_state = 8},
  [42] = {.lex_state = 0, .external_lex_state = 9},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0, .external_lex_state = 9},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0, .external_lex_state = 10},
};

enum {
  ts_external_token__newline = 0,
  ts_external_token__newline_plus = 1,
  ts_external_token_head3 = 2,
  ts_external_token_head2 = 3,
  ts_external_token_head1 = 4,
  ts_external_token_fence_open = 5,
  ts_external_token_fence_close = 6,
  ts_external_token_code_lang = 7,
  ts_external_token__code_line = 8,
  ts_external_token_text = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__newline_plus] = sym__newline_plus,
  [ts_external_token_head3] = sym_head3,
  [ts_external_token_head2] = sym_head2,
  [ts_external_token_head1] = sym_head1,
  [ts_external_token_fence_open] = sym_fence_open,
  [ts_external_token_fence_close] = sym_fence_close,
  [ts_external_token_code_lang] = sym_code_lang,
  [ts_external_token__code_line] = sym__code_line,
  [ts_external_token_text] = sym_text,
};

static const bool ts_external_scanner_states[11][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_head3] = true,
    [ts_external_token_head2] = true,
    [ts_external_token_head1] = true,
    [ts_external_token_fence_open] = true,
    [ts_external_token_fence_close] = true,
    [ts_external_token_code_lang] = true,
    [ts_external_token__code_line] = true,
    [ts_external_token_text] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token_head3] = true,
    [ts_external_token_head2] = true,
    [ts_external_token_head1] = true,
    [ts_external_token_fence_open] = true,
    [ts_external_token_text] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_head3] = true,
    [ts_external_token_head2] = true,
    [ts_external_token_head1] = true,
    [ts_external_token_fence_open] = true,
    [ts_external_token_text] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
    [ts_external_token__newline_plus] = true,
    [ts_external_token_text] = true,
  },
  [5] = {
    [ts_external_token_text] = true,
  },
  [6] = {
    [ts_external_token_fence_close] = true,
    [ts_external_token__code_line] = true,
  },
  [7] = {
    [ts_external_token__code_line] = true,
  },
  [8] = {
    [ts_external_token__newline] = true,
    [ts_external_token_code_lang] = true,
  },
  [9] = {
    [ts_external_token_fence_close] = true,
  },
  [10] = {
    [ts_external_token__newline] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__newline_plus] = ACTIONS(1),
    [sym_head3] = ACTIONS(1),
    [sym_head2] = ACTIONS(1),
    [sym_head1] = ACTIONS(1),
    [sym_fence_open] = ACTIONS(1),
    [sym_fence_close] = ACTIONS(1),
    [sym_code_lang] = ACTIONS(1),
    [sym__code_line] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(43),
    [sym__block] = STATE(3),
    [sym_chapter] = STATE(3),
    [sym_section] = STATE(3),
    [sym_subsection] = STATE(3),
    [sym_code_block_lang] = STATE(3),
    [sym_code_block] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym__inline] = STATE(4),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_monospaced] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [sym__newline] = ACTIONS(5),
    [sym_head3] = ACTIONS(13),
    [sym_head2] = ACTIONS(15),
    [sym_head1] = ACTIONS(17),
    [sym_fence_open] = ACTIONS(19),
    [sym_text] = ACTIONS(5),
  },
  [2] = {
    [sym__block] = STATE(2),
    [sym_chapter] = STATE(2),
    [sym_section] = STATE(2),
    [sym_subsection] = STATE(2),
    [sym_code_block_lang] = STATE(2),
    [sym_code_block] = STATE(2),
    [sym_paragraph] = STATE(2),
    [sym__inline] = STATE(4),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_monospaced] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_comment] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(26),
    [anon_sym__] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(32),
    [sym__newline] = ACTIONS(23),
    [sym_head3] = ACTIONS(35),
    [sym_head2] = ACTIONS(38),
    [sym_head1] = ACTIONS(41),
    [sym_fence_open] = ACTIONS(44),
    [sym_text] = ACTIONS(23),
  },
  [3] = {
    [sym__block] = STATE(2),
    [sym_chapter] = STATE(2),
    [sym_section] = STATE(2),
    [sym_subsection] = STATE(2),
    [sym_code_block_lang] = STATE(2),
    [sym_code_block] = STATE(2),
    [sym_paragraph] = STATE(2),
    [sym__inline] = STATE(4),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_monospaced] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_comment] = ACTIONS(5),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [sym__newline] = ACTIONS(5),
    [sym_head3] = ACTIONS(13),
    [sym_head2] = ACTIONS(15),
    [sym_head1] = ACTIONS(17),
    [sym_fence_open] = ACTIONS(19),
    [sym_text] = ACTIONS(5),
  },
  [4] = {
    [sym__inline] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_monospaced] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_comment] = ACTIONS(51),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [sym__newline] = ACTIONS(51),
    [sym__newline_plus] = ACTIONS(53),
    [sym_head3] = ACTIONS(49),
    [sym_head2] = ACTIONS(49),
    [sym_head1] = ACTIONS(49),
    [sym_fence_open] = ACTIONS(49),
    [sym_text] = ACTIONS(51),
  },
  [5] = {
    [sym__inline] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_monospaced] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_comment] = ACTIONS(57),
    [anon_sym_STAR] = ACTIONS(60),
    [anon_sym__] = ACTIONS(63),
    [anon_sym_BQUOTE] = ACTIONS(66),
    [sym__newline] = ACTIONS(57),
    [sym__newline_plus] = ACTIONS(55),
    [sym_head3] = ACTIONS(55),
    [sym_head2] = ACTIONS(55),
    [sym_head1] = ACTIONS(55),
    [sym_fence_open] = ACTIONS(55),
    [sym_text] = ACTIONS(57),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(71), 1,
      anon_sym_STAR,
    ACTIONS(73), 1,
      anon_sym__,
    ACTIONS(75), 1,
      anon_sym_BQUOTE,
    STATE(16), 1,
      sym__end_block,
    ACTIONS(69), 2,
      sym_text,
      sym_comment,
    ACTIONS(77), 2,
      sym__newline,
      sym__newline_plus,
    STATE(12), 5,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      aux_sym_chapter_repeat1,
  [28] = 7,
    ACTIONS(71), 1,
      anon_sym_STAR,
    ACTIONS(73), 1,
      anon_sym__,
    ACTIONS(75), 1,
      anon_sym_BQUOTE,
    STATE(17), 1,
      sym__end_block,
    ACTIONS(69), 2,
      sym_text,
      sym_comment,
    ACTIONS(79), 2,
      sym__newline,
      sym__newline_plus,
    STATE(12), 5,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      aux_sym_chapter_repeat1,
  [56] = 7,
    ACTIONS(71), 1,
      anon_sym_STAR,
    ACTIONS(73), 1,
      anon_sym__,
    ACTIONS(75), 1,
      anon_sym_BQUOTE,
    STATE(13), 1,
      sym__end_block,
    ACTIONS(69), 2,
      sym_text,
      sym_comment,
    ACTIONS(81), 2,
      sym__newline,
      sym__newline_plus,
    STATE(12), 5,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      aux_sym_chapter_repeat1,
  [84] = 1,
    ACTIONS(83), 12,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [99] = 1,
    ACTIONS(85), 12,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [114] = 1,
    ACTIONS(87), 12,
      sym__newline,
      sym__newline_plus,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [129] = 6,
    ACTIONS(92), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(98), 1,
      anon_sym_BQUOTE,
    ACTIONS(89), 2,
      sym_text,
      sym_comment,
    ACTIONS(101), 2,
      sym__newline,
      sym__newline_plus,
    STATE(12), 5,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      aux_sym_chapter_repeat1,
  [154] = 1,
    ACTIONS(103), 11,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [168] = 1,
    ACTIONS(105), 11,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [182] = 1,
    ACTIONS(107), 11,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [196] = 1,
    ACTIONS(109), 11,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [210] = 1,
    ACTIONS(111), 11,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [224] = 1,
    ACTIONS(113), 11,
      sym__newline,
      sym_head3,
      sym_head2,
      sym_head1,
      sym_fence_open,
      sym_text,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [238] = 5,
    ACTIONS(71), 1,
      anon_sym_STAR,
    ACTIONS(73), 1,
      anon_sym__,
    ACTIONS(75), 1,
      anon_sym_BQUOTE,
    ACTIONS(115), 2,
      sym_text,
      sym_comment,
    STATE(6), 5,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      aux_sym_chapter_repeat1,
  [259] = 5,
    ACTIONS(71), 1,
      anon_sym_STAR,
    ACTIONS(73), 1,
      anon_sym__,
    ACTIONS(75), 1,
      anon_sym_BQUOTE,
    ACTIONS(117), 2,
      sym_text,
      sym_comment,
    STATE(8), 5,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      aux_sym_chapter_repeat1,
  [280] = 5,
    ACTIONS(71), 1,
      anon_sym_STAR,
    ACTIONS(73), 1,
      anon_sym__,
    ACTIONS(75), 1,
      anon_sym_BQUOTE,
    ACTIONS(119), 2,
      sym_text,
      sym_comment,
    STATE(7), 5,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
      aux_sym_chapter_repeat1,
  [301] = 5,
    ACTIONS(123), 1,
      anon_sym_STAR,
    ACTIONS(125), 1,
      anon_sym__,
    ACTIONS(127), 1,
      anon_sym_BQUOTE,
    ACTIONS(121), 2,
      sym_text,
      sym_comment,
    STATE(49), 4,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
  [321] = 5,
    ACTIONS(123), 1,
      anon_sym_STAR,
    ACTIONS(125), 1,
      anon_sym__,
    ACTIONS(127), 1,
      anon_sym_BQUOTE,
    ACTIONS(129), 2,
      sym_text,
      sym_comment,
    STATE(48), 4,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
  [341] = 5,
    ACTIONS(123), 1,
      anon_sym_STAR,
    ACTIONS(125), 1,
      anon_sym__,
    ACTIONS(127), 1,
      anon_sym_BQUOTE,
    ACTIONS(131), 2,
      sym_text,
      sym_comment,
    STATE(47), 4,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
  [361] = 5,
    ACTIONS(123), 1,
      anon_sym_STAR,
    ACTIONS(125), 1,
      anon_sym__,
    ACTIONS(127), 1,
      anon_sym_BQUOTE,
    ACTIONS(133), 2,
      sym_text,
      sym_comment,
    STATE(46), 4,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
  [381] = 5,
    ACTIONS(123), 1,
      anon_sym_STAR,
    ACTIONS(125), 1,
      anon_sym__,
    ACTIONS(127), 1,
      anon_sym_BQUOTE,
    ACTIONS(135), 2,
      sym_text,
      sym_comment,
    STATE(45), 4,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
  [401] = 5,
    ACTIONS(123), 1,
      anon_sym_STAR,
    ACTIONS(125), 1,
      anon_sym__,
    ACTIONS(127), 1,
      anon_sym_BQUOTE,
    ACTIONS(137), 2,
      sym_text,
      sym_comment,
    STATE(44), 4,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
  [421] = 5,
    ACTIONS(123), 1,
      anon_sym_STAR,
    ACTIONS(125), 1,
      anon_sym__,
    ACTIONS(127), 1,
      anon_sym_BQUOTE,
    ACTIONS(139), 2,
      sym_text,
      sym_comment,
    STATE(51), 4,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
  [441] = 5,
    ACTIONS(123), 1,
      anon_sym_STAR,
    ACTIONS(125), 1,
      anon_sym__,
    ACTIONS(127), 1,
      anon_sym_BQUOTE,
    ACTIONS(141), 2,
      sym_text,
      sym_comment,
    STATE(52), 4,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
  [461] = 5,
    ACTIONS(123), 1,
      anon_sym_STAR,
    ACTIONS(125), 1,
      anon_sym__,
    ACTIONS(127), 1,
      anon_sym_BQUOTE,
    ACTIONS(143), 2,
      sym_text,
      sym_comment,
    STATE(53), 4,
      sym__inline,
      sym_bold,
      sym_italic,
      sym_monospaced,
  [481] = 1,
    ACTIONS(83), 7,
      sym__newline,
      sym__newline_plus,
      sym_text,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [491] = 1,
    ACTIONS(85), 7,
      sym__newline,
      sym__newline_plus,
      sym_text,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [501] = 1,
    ACTIONS(87), 7,
      sym__newline,
      sym__newline_plus,
      sym_text,
      sym_comment,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [511] = 3,
    ACTIONS(145), 1,
      sym_fence_close,
    ACTIONS(147), 1,
      sym__code_line,
    STATE(34), 1,
      aux_sym_code_content_repeat1,
  [521] = 3,
    ACTIONS(150), 1,
      sym__code_line,
    STATE(36), 1,
      aux_sym_code_content_repeat1,
    STATE(42), 1,
      sym_code_content,
  [531] = 3,
    ACTIONS(152), 1,
      sym_fence_close,
    ACTIONS(154), 1,
      sym__code_line,
    STATE(34), 1,
      aux_sym_code_content_repeat1,
  [541] = 1,
    ACTIONS(87), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [547] = 1,
    ACTIONS(85), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [553] = 1,
    ACTIONS(83), 3,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_BQUOTE,
  [559] = 3,
    ACTIONS(150), 1,
      sym__code_line,
    STATE(36), 1,
      aux_sym_code_content_repeat1,
    STATE(50), 1,
      sym_code_content,
  [569] = 2,
    ACTIONS(156), 1,
      sym__newline,
    ACTIONS(158), 1,
      sym_code_lang,
  [576] = 1,
    ACTIONS(160), 1,
      sym_fence_close,
  [580] = 1,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
  [584] = 1,
    ACTIONS(164), 1,
      anon_sym_STAR,
  [588] = 1,
    ACTIONS(166), 1,
      anon_sym__,
  [592] = 1,
    ACTIONS(168), 1,
      anon_sym_BQUOTE,
  [596] = 1,
    ACTIONS(170), 1,
      anon_sym_STAR,
  [600] = 1,
    ACTIONS(172), 1,
      anon_sym__,
  [604] = 1,
    ACTIONS(174), 1,
      anon_sym_BQUOTE,
  [608] = 1,
    ACTIONS(176), 1,
      sym_fence_close,
  [612] = 1,
    ACTIONS(178), 1,
      anon_sym_BQUOTE,
  [616] = 1,
    ACTIONS(180), 1,
      anon_sym__,
  [620] = 1,
    ACTIONS(182), 1,
      anon_sym_STAR,
  [624] = 1,
    ACTIONS(184), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 28,
  [SMALL_STATE(8)] = 56,
  [SMALL_STATE(9)] = 84,
  [SMALL_STATE(10)] = 99,
  [SMALL_STATE(11)] = 114,
  [SMALL_STATE(12)] = 129,
  [SMALL_STATE(13)] = 154,
  [SMALL_STATE(14)] = 168,
  [SMALL_STATE(15)] = 182,
  [SMALL_STATE(16)] = 196,
  [SMALL_STATE(17)] = 210,
  [SMALL_STATE(18)] = 224,
  [SMALL_STATE(19)] = 238,
  [SMALL_STATE(20)] = 259,
  [SMALL_STATE(21)] = 280,
  [SMALL_STATE(22)] = 301,
  [SMALL_STATE(23)] = 321,
  [SMALL_STATE(24)] = 341,
  [SMALL_STATE(25)] = 361,
  [SMALL_STATE(26)] = 381,
  [SMALL_STATE(27)] = 401,
  [SMALL_STATE(28)] = 421,
  [SMALL_STATE(29)] = 441,
  [SMALL_STATE(30)] = 461,
  [SMALL_STATE(31)] = 481,
  [SMALL_STATE(32)] = 491,
  [SMALL_STATE(33)] = 501,
  [SMALL_STATE(34)] = 511,
  [SMALL_STATE(35)] = 521,
  [SMALL_STATE(36)] = 531,
  [SMALL_STATE(37)] = 541,
  [SMALL_STATE(38)] = 547,
  [SMALL_STATE(39)] = 553,
  [SMALL_STATE(40)] = 559,
  [SMALL_STATE(41)] = 569,
  [SMALL_STATE(42)] = 576,
  [SMALL_STATE(43)] = 580,
  [SMALL_STATE(44)] = 584,
  [SMALL_STATE(45)] = 588,
  [SMALL_STATE(46)] = 592,
  [SMALL_STATE(47)] = 596,
  [SMALL_STATE(48)] = 600,
  [SMALL_STATE(49)] = 604,
  [SMALL_STATE(50)] = 608,
  [SMALL_STATE(51)] = 612,
  [SMALL_STATE(52)] = 616,
  [SMALL_STATE(53)] = 620,
  [SMALL_STATE(54)] = 624,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(4),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(30),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(29),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(28),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(19),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(21),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(20),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(41),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(5),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(30),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(29),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(28),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_monospaced, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(12),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(27),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(26),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2), SHIFT_REPEAT(25),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chapter_repeat1, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subsection, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block_lang, 5),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chapter, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_content_repeat1, 2),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_content_repeat1, 2), SHIFT_REPEAT(34),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_content, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [162] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_gularen_external_scanner_create(void);
void tree_sitter_gularen_external_scanner_destroy(void *);
bool tree_sitter_gularen_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_gularen_external_scanner_serialize(void *, char *);
void tree_sitter_gularen_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_gularen(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_gularen_external_scanner_create,
      tree_sitter_gularen_external_scanner_destroy,
      tree_sitter_gularen_external_scanner_scan,
      tree_sitter_gularen_external_scanner_serialize,
      tree_sitter_gularen_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
